### ISSUE TITLE
How do you get error log for typescript and not javascript

### ISSUE THREAD

**Issue by Safiyya** [monounity/karma-typescript#100]
Is there anyway to get the error log whenever a test fails to match the lines in `.ts` instead of the transpiled`.js`. 

For instance, i added this test in the `examples/angular2/src/hello.spec.ts` : 

```
it("should fail", ()=>{
        expect(true).toBe(false);
    });
```

`npm test` returns 
```
Chrome 56.0.2924 (Mac OS X 10.11.6) HelloComponent should fail FAILED
        Expected true to be false.
            at Object.<anonymous> (src/app/hello.spec.js:19:22) [ProxyZone]
            at ProxyZoneSpec.onInvoke (/var/folders/zb/j1f01h3d19321jxy1dvphvl40000gp/T/karma-typescript-bundle-59044Olnxo93kVB5F.js:8188:39
) [ProxyZone]
            at Zone.run (/var/folders/zb/j1f01h3d19321jxy1dvphvl40000gp/T/karma-typescript-bundle-59044Olnxo93kVB5F.js:6217:43) [ProxyZone =
> ProxyZone]
            at Object.<anonymous> (/var/folders/zb/j1f01h3d19321jxy1dvphvl40000gp/T/karma-typescript-bundle-59044Olnxo93kVB5F.js:8386:34) [P
roxyZone]
``` 

which is correct but not really helpful for debugging tests.

Am i missing a setting in the `karma.conf.js` ?

Thanks.

**Comment by erikbarke** [comment]
Hey @Safiyya, getting remapped errors and stacktraces seems to be the holy grail of unit testing transpiled languages, there's a lengthy discussion on the subject here: https://github.com/jasmine/jasmine/issues/491. Also, you could try playing around with https://github.com/evanw/node-source-map-support, I would love to hear what results you get.

**Comment by Safiyya** [comment]
Ah I see , I'm new to this. I will take a look at that library and see what I can I find.

**Comment by erikbarke** [comment]
Did you manage to get something working? I've tried the Typescript demo on the readme page for https://github.com/evanw/node-source-map-support and it works, but I get no results when I try it with karma-typescript...
