### ISSUE TITLE
Can not load "karma-typescript", it is not registered!

### ISSUE THREAD

**Issue by paulcoyle** [monounity/karma-typescript#101]
Seems similar to #8 but that issue appears to have been resolved.

I've tried this on 2.1.7, 2.1.8 (via branch url), and beta from npm (from info in #92) - all produce the same error. I've also tried adding `source-map` directly as noted in #8 but with no luck.  The only package installed that depends on `di` is karma itself.

Stack trace:
```bash
09 03 2017 16:35:27.528:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
  Perhaps you are missing some plugin?
/Users/pcoyle/Projects/project/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)
    at error (/Users/pcoyle/Projects/project/node_modules/di/lib/injector.js:22:12)
    at Object.get (/Users/pcoyle/Projects/project/node_modules/di/lib/injector.js:9:13)
    at Injector.get (/Users/pcoyle/Projects/project/node_modules/di/lib/injector.js:54:19)
    at /Users/pcoyle/Projects/project/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at Server._start (/Users/pcoyle/Projects/project/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/Users/pcoyle/Projects/project/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/pcoyle/Projects/project/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/Users/pcoyle/Projects/project/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/Users/pcoyle/Projects/project/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
```

Karma config:
```javascript
module.exports = function(config) {
  config.set({
    frameworks: [
      'jasmine',
      'karma-typescript'
    ],
    files: [
      { pattern: 'src/**/*.ts' }
    ],
    plugins: [
      'karma-jasmine',
      'karma-chrome-launcher'
    ],
    preprocessors: {
      '**/*.ts': ['karma-typescript']
    },
    reporters: ['progress', 'karma-typescript'],
    browsers: ['Chrome']
  })
}
```

Relevant dependencies:
```json
{
    "jasmine-core": "^2.5.2",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.1.0",
    "typescript": "^2.2.1",
}
```

**Comment by erikbarke** [comment]
Hey @paulcoyle, here's the culprit:

```js
plugins: [
    'karma-jasmine',
    'karma-chrome-launcher'
],
```
Either add 'karma-typescript' to the array or remove the array entirely, Karma loads plugins starting with `karma-*` by default.

**Comment by Shavindra** [comment]
I am getting the error even without plugins[]

**Comment by Shavindra** [comment]
I managed to fix it by reverting to `2.0.9` and installing ` "karma-chrome-launcher": "^2.0.0"`
`

**Comment by erikbarke** [comment]
@paulcoyle, @Shavindra, what `Karma` and `npm` versions are you using? I have two integration test suites and five example projects that compile and run on [Travis](https://travis-ci.org/monounity/karma-typescriptl), [Appveyor](https://ci.appveyor.com/project/monounity/karma-typescript) and my machine (OS X), so I'm wondering what the differences are between your environments and those where it just works.

**Comment by aparkerw** [comment]
I have the same issue.  npm version **4.4.1**   and karma version **1.5.0**

I also tried the fix from #8 to install `source-map` without luck

![image](https://cloud.githubusercontent.com/assets/649430/23884116/342dcb78-0841-11e7-82d6-569847e2a4d2.png)


Here is my `karma.conf.js`.  Slightly different:
```
module.exports = function(config) {
    config.set({
        frameworks: ["jasmine", "karma-typescript"],
        files: [
            { pattern: "src/**/*.ts" },
        ],
        preprocessors: {
            "**/*.ts": ["karma-typescript"],
        },
        reporters: ["progress", "karma-typescript"],
        browsers: ["Chrome"]
    });
};
```

**Comment by erikbarke** [comment]
What does the output before `ERROR [preprocess]: Can not load "karma-typescript", it is not registered!` look like, any other error messages etc?

Does it work if you make a clean install somewhere in your file system and run one of the example projects?

```bash
npm i karma-typescript@beta
cd node_modules/karma-typescript/
npm i
cd examples/angular2/
npm i
npm test
```

**Comment by erikbarke** [comment]
@paulcoyle, @Shavindra, @aparkerw, did you manage to get past this error? If not, is it related to this issue, https://github.com/karma-runner/karma/issues/2524?

**Comment by erikbarke** [comment]
Closing due to inactivity.

**Comment by francoislg** [comment]
Just for reference, was using *karma-typescript@2.1.7* and  *karma@1.5.0*, was getting this error. Upgraded to *karma-typescript@3.0.0-beta.2*, still getting the error.

Launched `rm -rf node_modules` then `npm install` again, and it started working.

**Comment by jnorkus** [comment]
Had the same issue because karma was running from global installation, but karma-typescript was only installed locally. `npm install -g karma-typescript` solved the issue for me.

**Comment by YX-XiaoBai** [comment]
it's doesn't work! need some help...
$ karma start karma.conf.js
11 11 2020 15:42:40.707:ERROR [plugin]: Cannot find plugin "/usr/local/lib/node_modules/karma-typescript".
  Did you forget to install it?
  npm install /usr/local/lib/node_modules/karma-typescript --save-dev
11 11 2020 15:42:40.717:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
  Perhaps you are missing some plugin?
11 11 2020 15:42:40.720:ERROR [karma-server]: Server start failed on port 9877: Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)

**Comment by YX-XiaoBai** [comment]
> it's doesn't work! need some help...
> $ karma start karma.conf.js
> 11 11 2020 15:42:40.707:ERROR [plugin]: Cannot find plugin "/usr/local/lib/node_modules/karma-typescript".
> Did you forget to install it?
> npm install /usr/local/lib/node_modules/karma-typescript --save-dev
> 11 11 2020 15:42:40.717:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
> Perhaps you are missing some plugin?
> 11 11 2020 15:42:40.720:ERROR [karma-server]: Server start failed on port 9877: Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)

here it's my `karma.conf.js`:

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ["jasmine", "karma-typescript"],
    files: [
      './src/*/*.ts',
      './test/*.spec.js'
    ],
    exclude: [
      'karma.conf.js'
    ],
    preprocessors: {
      "./src/*/*.ts": ["karma-typescript"] // *.tsx for React Jsx
    },
    reporters: ["progress", "karma-typescript"],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    concurrency: Infinity
  })
}

**Comment by RASMiranda** [comment]
> > it's doesn't work! need some help...
> > $ karma start karma.conf.js
> > 11 11 2020 15:42:40.707:ERROR [plugin]: Cannot find plugin "/usr/local/lib/node_modules/karma-typescript".
> > Did you forget to install it?
> > npm install /usr/local/lib/node_modules/karma-typescript --save-dev
> > 11 11 2020 15:42:40.717:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
> > Perhaps you are missing some plugin?
> > 11 11 2020 15:42:40.720:ERROR [karma-server]: Server start failed on port 9877: Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)
> 
> here it's my `karma.conf.js`:
> 
> ```js
> module.exports = function (config) {
>   config.set({
>     basePath: '',
>     frameworks: ["jasmine", "karma-typescript"],
>     files: [
>       './src/*/*.ts',
>       './test/*.spec.js'
>     ],
>     exclude: [
>       'karma.conf.js'
>     ],
>     preprocessors: {
>       "./src/*/*.ts": ["karma-typescript"] // *.tsx for React Jsx
>     },
>     reporters: ["progress", "karma-typescript"],
>     port: 9876,
>     colors: true,
>     logLevel: config.LOG_INFO,
>     autoWatch: true,
>     browsers: ['Chrome'],
>     singleRun: false,
>     concurrency: Infinity
>   })
> }
> ```

You are missing the plugin require:
```
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ["jasmine", "karma-typescript"],
    plugins: [
      require('karma-typescript') // Missing plugin require here
    ],
    files: [
      './src/*/*.ts',
      './test/*.spec.js'
    ],
    exclude: [
      'karma.conf.js'
    ],
    preprocessors: {
      "./src/*/*.ts": ["karma-typescript"] // *.tsx for React Jsx
    },
    reporters: ["progress", "karma-typescript"],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    concurrency: Infinity
  })
}
```
