### ISSUE TITLE
Installing some modules throws errors

### ISSUE THREAD

**Issue by hadrien-toma** [monounity/karma-typescript#104]
Hi there, I have some troubles trying to use your (**super usefull**) plugin.
### Modules throwing errors:
* "clear": "0.0.1"
* "github": "^9.1.0" & "@types/github": "0.0.0"
* "rxjs": "^5.2.0"
* "nodegit": "^0.18.0"

### Steps to reproduce:
```bash
git clone https://github.com/monounity/karma-typescript.git
cd karma-typescript/examples/typescript-latest
npm install
npm test
```
All this works perfectly. Than I `npm install` one of the modules quoted previously, import it in `hello.component.ts` and finally get some errors when `npm test`. These errors are described in the following section.

### Errors according to installed module:
* "clear": "0.0.1":
**Breaking errors:**
```
23 03 2017 07:21:40.253:ERROR [karma]: { SyntaxError: Octal literal in strict mode (3:26)
    at Parser.pp$4.raise (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp$7.readEscapedChar (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:3280:14)
    at Parser.pp$7.readString (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:3192:21)
    at Parser.pp$7.getTokenFromCode (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:2980:17)
    at Parser.pp$7.readToken (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:2733:15)
    at Parser.pp$7.nextToken (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:2724:13)
    at Parser.pp$7.next (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:2684:8)
    at Parser.pp.eat (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:555:10)
    at Parser.pp$3.parseSubscripts (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1896:35)
    at Parser.pp$3.parseExprSubscripts (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1875:21)
    at Parser.pp$3.parseMaybeUnary (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1849:17)
    at Parser.pp$3.parseExprOps (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1791:19)
    at Parser.pp$3.parseMaybeConditional (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1774:19)
    at Parser.pp$3.parseMaybeAssign (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1750:19)
    at Parser.pp$3.parseExpression (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:1722:19)
    at Parser.pp$1.parseStatement (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/acorn/dist/acorn.js:777:45) pos: 86, loc: Position { line: 3, column: 26 }, raisedAt: 88 }
npm ERR! Test failed.  See above for more details.
```
* "github": "^9.1.0" & "@types/github": "0.0.0":
**Not breaking errors:**
```
23 03 2017 07:35:45.086:ERROR [compiler.karma-typescript]: node_modules/@types/github/index.d.ts(50,22): error TS2693: 'Promise' only refers to a type, but is being used as a value here.

23 03 2017 07:35:45.087:ERROR [compiler.karma-typescript]: node_modules/github/lib/index.d.ts(25,22): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
```
* "rxjs": "^5.2.0":
**Not breaking errors:**
```
23 03 2017 07:43:34.712:ERROR [compiler.karma-typescript]: node_modules/rxjs/Observable.d.ts(69,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.

23 03 2017 07:43:34.713:ERROR [compiler.karma-typescript]: node_modules/rxjs/operator/toPromise.d.ts(3,79): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
```
* "nodegit": "^0.18.0":
**Breaking errors:**
```
Error: Cannot find module './utils' from '/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/nodegit/dist'
    at /home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:93:23
    at /home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/browser-resolve/index.js:265:24
    at /home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/hadrien-toma/dev/nodejs/karma-typescript/examples/typescript-latest/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)
npm ERR! Test failed.  See above for more details.
```
### Questions
Do you know if I have to add special configuration to my `karma.conf.js` / `tsconfig.json` or maybe you have an idea of what I can do to fix these errors? In any case, let me thank you for the work you have already done here!

**Comment by erikbarke** [comment]
Hey @hadrien-toma, I'll take a look and get back to you!

**Comment by erikbarke** [comment]
I get past all the compiler and bundler errors but now I get runtime errors which I suspect are due to me not fully understanding how to install `nodegit` correctly.

The following assumes you have the latest from master:
```js
karmaTypescriptConfig: {
    bundlerOptions: {
        noParse: ["clear"] // fix for "SyntaxError: Octal literal in strict mode"
    },
    compilerOptions: {
        lib: ["es2017", "dom"] // fix for "'Promise' only refers to a type"
    }
}
```

**Comment by hadrien-toma** [comment]
Hey @erikbarke, thank you for your help! I still have an error with `nodegit` when not having any at runtime (using the latest from master and the advanced config you gave me). The error I have is now different:
```
26 03 2017 22:46:42.651:ERROR [karma]: Error: Unable to resolve module [../build/Debug/nodegit.node] from [/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/nodegit/dist/nodegit.js]
{
  "extensions": [
    ".js",
    ".json",
    ".ts",
    ".tsx"
  ],
  "filename": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/nodegit/dist/nodegit.js",
  "moduleDirectory": [
    "node_modules"
  ],
  "modules": {
    "assert": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/assert/assert.js",
    "buffer": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/buffer/index.js",
    "child_process": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "cluster": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "console": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/console-browserify/index.js",
    "constants": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/constants-browserify/constants.json",
    "crypto": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/crypto-browserify/index.js",
    "dgram": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "dns": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "domain": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/domain-browser/index.js",
    "events": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/events/events.js",
    "fs": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "http": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/stream-http/index.js",
    "https": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/https-browserify/index.js",
    "module": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "net": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "os": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/os-browserify/browser.js",
    "path": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/path-browserify/index.js",
    "punycode": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/punycode/punycode.js",
    "querystring": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/querystring-es3/index.js",
    "readline": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "repl": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "stream": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/stream-browserify/index.js",
    "_stream_duplex": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/readable-stream/duplex.js",
    "_stream_passthrough": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/readable-stream/passthrough.js",
    "_stream_readable": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/readable-stream/readable.js",
    "_stream_transform": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/readable-stream/transform.js",
    "_stream_writable": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/readable-stream/writable.js",
    "string_decoder": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/string_decoder/index.js",
    "sys": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/util/util.js",
    "timers": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/timers-browserify/main.js",
    "tls": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "tty": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/tty-browserify/index.js",
    "url": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/url/url.js",
    "util": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/util/util.js",
    "vm": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/vm-browserify/index.js",
    "zlib": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/browserify-zlib/src/index.js",
    "_process": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/process/browser.js"
  },
  "basedir": "/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/nodegit/dist",
  "paths": []
}
Error: Cannot find module '../build/Debug/nodegit.node' from '/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/nodegit/dist'
    at /home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:101:23
    at /home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/browser-resolve/index.js:265:24
    at /home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/hadrien-toma/dev/nodejs/optoruta_step_by_step/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:114:15)
26 03 2017 22:46:42.659:DEBUG [launcher]: Disconnecting all browsers

npm ERR! Linux 3.19.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "utest"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! @hadrien-toma/_optoruta@1.0.0 utest: `./node_modules/karma/bin/karma start --log-level $npm_package_config_mode`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @hadrien-toma/_optoruta@1.0.0 utest script './node_modules/karma/bin/karma start --log-level $npm_package_config_mode'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @hadrien-toma/_optoruta package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/karma/bin/karma start --log-level $npm_package_config_mode
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @hadrien-toma/_optoruta
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @hadrien-toma/_optoruta
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/hadrien-toma/dev/nodejs/optoruta_step_by_step/npm-debug.log
npm ERR! Test failed.  See above for more details.
```
I don't know what would be the best way for you to reproduce it. Do you have an idea? My environment is:
```
> uname -a
Linux hadrien-toma-kde 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
> cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
```

**Comment by erikbarke** [comment]
That's the error I got as well, I tried working around it by excluding the module:

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        exclude: ["../build/Debug/nodegit.node"],
        noParse: ["clear"] // fix for "SyntaxError: Octal literal in strict mode"
    },
    compilerOptions: {
        lib: ["es2017", "dom"] // fix for "'Promise' only refers to a type"
    }
}
```

But then it tries to load `../build/Release/nodegit.node` instead, which is a binary. This is what I meant when I said don't fully understand `nodegit`, I did an `npm install nodegit` and that didn't install the debug version on my system, but the code expects it to be there. Since you're getting the same error as me I'm quite sure now `nodegit` isn't supposed to be run in a web browser at all, which is a prerequisite for running tests with Karma.

**Comment by hadrien-toma** [comment]
Okay I see now. You are totally right : `nodegit` isn't supposed to be run in a web browser. I will switch to a a `jasmine` runner not designed for web browsers. For the moment, I unfortunately only know `Karma` and `Testem` to run unit tests, I will check if `Testem` would be convenient and otherwise... I will search for something else. I think you can close this issue as, in my point of view, you perfectly answered my issue. Thank you again!
