### ISSUE TITLE
Dependencies missing when using yarn

### ISSUE THREAD

**Issue by dirkluijk** [monounity/karma-typescript#106]
This is my package.json:

```
{
  "name": "karma-ts-playground",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/angular": "^1.5.20",
    "@types/angular-mocks": "^1.5.6",
    "@types/jasmine": "^2.5.38",
    "angular": "^1.5.8",
    "angular-mocks": "^1.5.8",
    "istanbul": "^0.4.5",
    "jasmine-core": "^2.5.2",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-typescript": "beta",
    "typescript": "latest"
  }
}
```

When using ``npm install`` everything works correct, but then I use ``yarn`` to install my dependencies, I got:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 2 of 2 SUCCESS (0.003 secs / 0.017 secs)
24 03 2017 13:20:38.454:ERROR [reporter.karma-typescript]: { Error: ENOENT: no such file or directory, scandir '/Users/dirkluijk/Desktop/karma-ts-playground/node_modules/istanbul/lib/assets'
    at Object.fs.readdirSync (fs.js:914:18)
    at copyAssets (/Users/dirkluijk/Desktop/karma-ts-playground/node_modules/istanbul/lib/report/html.js:543:20)
...
```

Any ideas? What must be added to support yarn as well?

**Comment by dirkluijk** [comment]
Solved. See https://github.com/gotwarlost/istanbul/issues/743

I have to remove my .yarnclean file. 👍
