### ISSUE TITLE
Typerror: not a function

### ISSUE THREAD

**Issue by kunal3** [monounity/karma-typescript#125]
I'm new to frontend development and trying to set up unit testing for our Angular2 app. I followed the setup instructions and I keep getting this error - 
```
30 05 2017 16:39:18.292:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.0.10
30 05 2017 16:39:22.016:INFO [compiler.karma-typescript]: Compiled 76 files in 3658 ms.
30 05 2017 16:39:23.433:ERROR [karma]: TypeError: this.moduleName.charAt is not a function
    at BundleItem.isNpmModule (/Users/kunal/Project1/web-client/node_modules/karma-typescript/dist/bundler/bundle-item.js:12:32)
    at Resolver.resolveModule (/Users/kunal/Project1/web-client/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:25:44)
    at /Users/kunal/Project1/web-client/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:106:27
    at /Users/kunal/Project1/web-client/node_modules/async/dist/async.js:3060:16
    at eachOfArrayLike (/Users/kunal/Project1/web-client/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/kunal/Project1/web-client/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/kunal/Project1/web-client/node_modules/async/dist/async.js:3122:5)
    at /Users/kunal/Project1/web-client/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:104:23
    at /Users/kunal/Project1/web-client/node_modules/karma-typescript/dist/bundler/dependency-walker.js:74:13
    at /Users/kunal/Project1/web-client/node_modules/karma-typescript/dist/bundler/dependency-walker.js:106:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Test failed.  See above for more details.
```
Any ideas on what could be causing it?

**Comment by erikbarke** [comment]
Hey @kunal3, could you run your project with Karma in debug mode, `logLevel: config.LOG_DEBUG`, and attach the output as a text file here please?

**Comment by kunal3** [comment]
Attached
[karma_log.txt](https://github.com/monounity/karma-typescript/files/1041975/karma_log.txt)

**Comment by erikbarke** [comment]
I've added an extra sanity check in the dependency walker, does it work for you if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by kunal3** [comment]
No luck. Same error. I ran 
```npm i github:monounity/karma-typescript#next --save-dev```
Attached new debug log - 
[karma_log_1.txt](https://github.com/monounity/karma-typescript/files/1042802/karma_log_1.txt)

**Comment by erikbarke** [comment]
Ok, I've managed to repro the error by adding `require(false)` (!) to a node_modules package... I've added some error logging, could you try again with `npm i github:monounity/karma-typescript#next` please?

**Comment by kunal3** [comment]
Got more errors this time, including the first one. The commands I run are -
```
npm run clean
npm i github:monounity/karma-typescript#next --save-dev
npm install
npm test
```
where clean is ```rimraf node_modules doc dist && npm cache clean```
and test is ```karma start karma.conf.js```

New errors - 
```
31 05 2017 17:45:51.532:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.0.10
31 05 2017 17:45:55.502:INFO [compiler.karma-typescript]: Compiled 76 files in 3916 ms.
31 05 2017 17:45:56.781:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 6
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.781:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 5
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 2
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 4
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 28
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 26
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 42
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 22
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 31
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 25
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 21
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 23
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 24
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.782:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 29
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.783:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 33
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.783:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 34
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.783:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 32
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.783:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 35
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.783:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 30
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.783:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 27
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.784:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 36
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.784:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 37
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.784:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 38
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.784:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 39
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.784:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 40
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.784:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 45
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 43
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 44
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 46
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 47
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 48
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 15
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 16
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 17
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.785:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 18
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 19
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 20
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 8
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 9
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 10
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 11
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 12
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 13
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 14
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.786:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 3
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.787:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 41
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.787:ERROR [dependency-walker.karma-typescript]: Unexpected literal value: 1
Required by: /Users/kunal/Quantifi/web-client/node_modules/chart.js/dist/chart.js
31 05 2017 17:45:56.790:ERROR [karma]: TypeError: this.moduleName.charAt is not a function
    at BundleItem.isNpmModule (/Users/kunal/Quantifi/web-client/node_modules/karma-typescript/dist/bundler/bundle-item.js:12:32)
    at Resolver.resolveModule (/Users/kunal/Quantifi/web-client/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:28:44)
    at /Users/kunal/Quantifi/web-client/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:109:27
    at /Users/kunal/Quantifi/web-client/node_modules/async/dist/async.js:3060:16
    at eachOfArrayLike (/Users/kunal/Quantifi/web-client/node_modules/async/dist/async.js:1003:9)
    at eachOf (/Users/kunal/Quantifi/web-client/node_modules/async/dist/async.js:1051:5)
    at Object.eachLimit (/Users/kunal/Quantifi/web-client/node_modules/async/dist/async.js:3122:5)
    at /Users/kunal/Quantifi/web-client/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:107:23
    at /Users/kunal/Quantifi/web-client/node_modules/karma-typescript/dist/bundler/dependency-walker.js:77:13
    at /Users/kunal/Quantifi/web-client/node_modules/karma-typescript/dist/bundler/dependency-walker.js:109:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Test failed.  See above for more details.
```

Attached new debug log - 
[karma_log_2.txt](https://github.com/monounity/karma-typescript/files/1043019/karma_log_2.txt)

**Comment by erikbarke** [comment]
Now we're getting somewhere! You're obviously using `chart.js` but how are you importing it? If I import it using the package name it works:
`import * as chart from "chart.js"; // works`

But if I import from the dist folder it breaks, because the dist version is already bundled which wont play nice with other bundlers:
`import * as chart from "chart.js/dist/Chart.js"; // crash and burn`

Having said that, I haven't actually tried executing any functions from the package, but it seems you're not alone in having trouble using chart.js with a bundler: https://github.com/valor-software/ng2-charts/issues/458.

**Comment by kunal3** [comment]
Ah changing from 
```import 'chart.js/dist/chart';``` to ```import chart.js``` in my vendor.ts made it go away! New error -

```
Chrome 58.0.3029 (Mac OS X 10.12.5) ERROR
  Uncaught ReferenceError: Zone is not defined
  at /var/folders/66/wgldd4n15f5b4gzz6f9fcv9h0000gn/T/karma-typescript-bundle-25666dBvZeG6I6zfR.js:41903
```
This might actually be something to do with my project and not your repo, can you confirm?

**Comment by erikbarke** [comment]
Ok, great 🎉 Regarding the `Zone` error, you need to include that lib either in the Karma file section or as imports like in [/examples/angular2/base.spec.ts](https://github.com/monounity/karma-typescript/blob/master/examples/angular2/base.spec.ts)!

**Comment by erikbarke** [comment]
v3.0.3 is on npm now!
