### ISSUE TITLE
Angular2 example doesn't work (anymore)

### ISSUE THREAD

**Issue by bbottema** [monounity/karma-typescript#131]
I followed the exact steps listed on the Angular2 page, but this is the result when I run `npm test`:

> 08 06 2017 20:21:01.155:ERROR [plugin]: Error during loading "D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules/karma-typescript" plugin:
  Cannot find module 'typescript'
08 06 2017 20:21:01.155:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
  Perhaps you are missing some plugin?
D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\di\lib\injector.js:9
      throw error('No provider for "' + name + '"!');
      ^
>
>Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)
    at error (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\di\lib\injector.js:22:12)
    at Object.get (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\di\lib\injector.js:9:13)
    at Injector.get (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\di\lib\injector.js:54:19)
    at D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\karma\lib\server.js:143:20
    at Array.forEach (native)
    at Server._start (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\karma\lib\server.js:142:21)
    at Injector.invoke (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\di\lib\injector.js:75:15)
    at Server.start (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\karma\lib\server.js:103:18)
    at Object.exports.run (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\karma\lib\cli.js:280:26)
    at Object.<anonymous> (D:\workstation\karmatest\node_modules\karma-typescript\examples\angular2\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

**Comment by erikbarke** [comment]
Hey @bbottema, this is weird! Most of the examples (including the Angular2 example) run on both Travis CI and on [AppVeyor](https://ci.appveyor.com/project/monounity/karma-typescript) after every push to this repo... Also, I just tried following the instructions for running the Angular2 example on my laptop and it ran just fine.

The Karma process on your end complains about `Cannot find module 'typescript'`, did it get installed properly when you ran `npm install`?

**Comment by bbottema** [comment]
Strange indeed. Yes install is simple and successful, using Webpack 2.6.1, Node 6.10.2, npm 5.0.3.

However, my situation was resolved some other way, so if you can't reproduce, then I suggest to close it.

**Comment by marmelin** [comment]
Hi guys, 
I want to wake this one up, because I have this exact same problem. It does not work even after first installation. 

```
# npm test

> karma-typescript-examples-angular2@3.0.7 test /home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2
> karma start

18 10 2017 13:24:24.917:ERROR [plugin]: Error during loading "/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/karma-typescript" plugin:
  Cannot find module 'typescript'
18 10 2017 13:24:24.922:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
  Perhaps you are missing some plugin?
/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)
    at error (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/di/lib/injector.js:22:12)
    at Object.get (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/di/lib/injector.js:9:13)
    at Injector.get (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/di/lib/injector.js:54:19)
    at /home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/karma/lib/server.js:143:20
    at Array.forEach (<anonymous>:null:null)
    at Server._start (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/karma/lib/server.js:142:21)
    at Injector.invoke (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/di/lib/injector.js:75:15)
    at Server.start (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/home/python1/Development/temp/karma-test/node_modules/karma-typescript/examples/angular2/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

npm ERR! Test failed.  See above for more details.
```

package.json:
```
{
  "name": "karma-typescript-examples-angular2",
  "version": "3.0.7",
  "description": "Example project for Angular2",
  "author": "monounity",
  "contributors": [
    {
      "name": "erikbarke"
    }
  ],
  "private": true,
  "license": "MIT",
  "scripts": {
    "dev": "gulp dev --cwd . && karma start",
    "dev:ci": "gulp dev:ci --cwd . && karma start --single-run",
    "dev:ci:phantomjs": "gulp dev:ci --cwd . && karma start --browsers PhantomJS --single-run",
    "test": "karma start"
  },
  "dependencies": {
    "@angular/common": "^4.0.3",
    "@angular/compiler": "^4.0.3",
    "@angular/core": "^4.0.3",
    "@angular/platform-browser": "^4.0.3",
    "@angular/platform-browser-dynamic": "^4.0.3",
    "@types/core-js": "^0.9.39",
    "@types/jasmine": "^2.5.37",
    "@types/node": "^7.0.13",
    "core-js": "^2.4.1",
    "jasmine-core": "^2.6.0",
    "karma": "^1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-jasmine": "^1.0.2",
    "rxjs": "^5.3.0",
    "zone.js": "^0.8.8"
  },
  "devDependencies": {
    "gulp": "^3.9.1",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-typescript": "file:../..",
    "karma-typescript-angular2-transform": "^1.0.2",
    "typescript": "^2.5.3"
  }
}
```

Any more suggestions on this?

**Comment by erikbarke** [comment]
@marmelin, as stated earlier in this thread, the Angular2 example runs on both Travis CI and on [AppVeyor](https://ci.appveyor.com/project/monounity/karma-typescript) after every push to this repo. You have the same error message as `bbottema` had, `Cannot find module 'typescript'`, can you verify that typescript package has been installed properly by npm?

**Comment by mitchhentges** [comment]
@marmelin, two suggestions that might help:

1. Are you running off the `master` branch? There's been some weird shenanigans with the compiled output existing in the repository, which should be resolved in `next`.
2. Did you run the [`install.[sh|bat]`](https://github.com/monounity/karma-typescript/blob/e6459401f6210502a2677850fc07abac85900f75/ci/install.sh) script? Perhaps running that will resolve the issue
