### ISSUE TITLE
ts.isDeclarationFile is not a function

### ISSUE THREAD

**Issue by rolandjitsu** [monounity/karma-typescript#135]
I think with the latest changes in TS `v2.4`, some of the APIs are gone, hence the error:

```text
12 06 2017 22:51:36.120:ERROR [karma]: TypeError: ts.isDeclarationFile is not a function
    at /Users/rolandjitsu/Projects/potion-node/node_modules/karma-typescript/dist/compiler/compiler.js:71:39
    at Array.forEach (native)
    at Compiler.onProgramCompiled (/Users/rolandjitsu/Projects/potion-node/node_modules/karma-typescript/dist/compiler/compiler.js:64:24)
    at Compiler.compileProject (/Users/rolandjitsu/Projects/potion-node/node_modules/karma-typescript/dist/compiler/compiler.js:50:14)
    at Compiler.<anonymous> (/Users/rolandjitsu/Projects/potion-node/node_modules/karma-typescript/dist/compiler/compiler.js:26:23)
    at invokeFunc (/Users/rolandjitsu/Projects/potion-node/node_modules/lodash/lodash.js:10350:23)
    at trailingEdge (/Users/rolandjitsu/Projects/potion-node/node_modules/lodash/lodash.js:10397:18)
    at Timeout.timerExpired [as _onTimeout] (/Users/rolandjitsu/Projects/potion-node/node_modules/lodash/lodash.js:10385:18)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by erikbarke** [comment]
Hey @rolandjitsu, I've committed a fix for this now, does it work for you if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by rolandjitsu** [comment]
@erikbarke I'll try it later and let you know if that works.

**Comment by rolandjitsu** [comment]
It works. So I guess you can publish on NPM ...

**Comment by erikbarke** [comment]
Ok, closing 😃

**Comment by rolandjitsu** [comment]
Do you think it'd be possible to publish a fix for this within the day? I cannot publish some of my packages due to failing tests 😆

**Comment by erikbarke** [comment]
The milestone 3.0.4 is 100% done now so I should be able to release today or tomorrow!

**Comment by erikbarke** [comment]
3.0.4 is on npm now!

**Comment by rolandjitsu** [comment]
Just updated 🎉 , thanks!
