### ISSUE TITLE
Error "Unable to resolve module [uuid/v4] from [.../mockgoose.js]"

### ISSUE THREAD

**Issue by holotrek** [monounity/karma-typescript#168]
My environment:

|OS/Software|Name and Version|
|---|---|
|OS|Windows 10|
|Node|6.11.0|
|NPM|5.3.0|
|MS Typescript (global)|2.4|

Please see / try out [this repository](https://github.com/holotrek/ts-node-rest-api/tree/feature/tests) (MongoDB not required for testing).

When attempting to run tests, I receive the error:
```
28 08 2017 10:45:33.802:ERROR [karma]: Error: Unable to resolve module [uuid/v4] from [C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\mockgoose\built\mockgoose.js]
{
  "extensions": [
    ".js",
    ".json",
    ".ts",
    ".tsx"
  ],
  "filename": "",
  "moduleDirectory": [
    "node_modules"
  ],
  "modules": {
    "assert": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\assert\\assert.js",
    "buffer": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\buffer\\index.js",
    "child_process": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "cluster": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "console": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\console-browserify\\index.js",
    "constants": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\constants-browserify\\constants.json",
    "crypto": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\crypto-browserify\\index.js",
    "dgram": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "dns": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "domain": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\domain-browser\\index.js",
    "events": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\events\\events.js",
    "fs": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "http": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\stream-http\\index.js",
    "https": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\https-browserify\\index.js",
    "module": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "net": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "os": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\os-browserify\\browser.js",
    "path": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\path-browserify\\index.js",
    "punycode": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\punycode\\punycode.js",
    "querystring": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\querystring-es3\\index.js",
    "readline": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "repl": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "stream": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\stream-browserify\\index.js",
    "_stream_duplex": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\readable-stream\\duplex.js",
    "_stream_passthrough": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\readable-stream\\passthrough.js",
    "_stream_readable": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\readable-stream\\readable.js",
    "_stream_transform": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\readable-stream\\transform.js",
    "_stream_writable": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\readable-stream\\writable.js",
    "string_decoder": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\string_decoder\\lib\\string_decoder.js",
    "sys": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\util\\util.js",
    "timers": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\timers-browserify\\main.js",
    "tls": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "tty": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\tty-browserify\\index.js",
    "url": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\url\\url.js",
    "util": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\util\\util.js",
    "vm": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\vm-browserify\\index.js",
    "zlib": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\browserify-zlib\\lib\\index.js",
    "_process": "C:\\Users\\kaisere\\Source\\Repos\\ts-node-rest-api\\node_modules\\process\\browser.js"
  },
  "basedir": ".",
  "paths": []
}
Error: Cannot find module 'uuid/v4' from '.'
    at C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\karma-typescript\dist\bundler\resolve\resolver.js:128:23
    at C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\index.js:265:24
    at C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:14
    at process (C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! Test failed.  See above for more details.
```

It appears that `uuid` is a dependency of `mockgoose`, so it is installed within that directory, not in the flat node_modules directory. Does karma-typescript not go recursively into package node_modules when loading the vendor libraries? 

It's really frustrating having to track down dependencies that are buried within other modules and install them separately. For example, after trying to install uuid separately `npm i -D uuid`, I then get these errors:
```
[karma]: Error: Unable to resolve module [lodash/noop] from [C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\async\eachOf.js]
```
```
[karma]: Error: Unable to resolve module [lodash/noop] from [C:\Users\kaisere\Source\Repos\ts-node-rest-api\node_modules\async\eachOf.js]
```

That process could take forever depending on how many dependencies I'd have to track down and install. Is there a config setting I'm missing to tell it to go into sub node_modules?

**Comment by erikbarke** [comment]
Hey @holotrek, it seems npm 5.x still has quite a lot of bugs; just glancing through the issue tracker there are quite a few issues regarding installs where npm nests some modules even though there are no conflicts. I tried using npm 5.3.0 and I had to revert to v4.6.1 to get your project to run without breaking the bundler, I couldn't even get the nodejs builtin `require.resolve` to resolve `uuid` correctly...

Having said that, I'm not sure your project will run at all in a web browser using karma, there are a lot of dependencies on packages using the file system which won't work in a browser environment 😞

**Comment by holotrek** [comment]
Thanks erikbarke for the quick response!

Thanks for the info. I'll try reverting to NPM 4 and how far I can get. I'm surprised that 5 still has so many bugs being in release for a few months.

In terms of the project files, I am specifically limiting the files being tested to the service and domain directories for that reason (only testing "plain" code), with the exception being the MongoDB access, which I have mocked with Mockgoose; hoping this works and doesn't do things the browser doesn't like, but I haven't gotten far enough in running the tests to see!

**Comment by holotrek** [comment]
An interesting note on this. If I deleted the package-lock.json and node_modules directory and then did a fresh install with NPM 5, it also seemed to work fine. Now I'm not sure what to think, other than maybe having a lock file is not the greatest idea, or that deleting node_modules/package-lock.json and trying again will become one of my standard debugging steps.
