### ISSUE TITLE
Failed to run test: "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by kalitine** [monounity/karma-typescript#184]
**karma**: v1.7.1
**karma-typescript**: v3.0.6
**typescript**: v2.5.2
[karma_debug.txt](https://github.com/monounity/karma-typescript/files/1313737/karma_debug.txt)

**Repo**: https://github.com/coast-team/netflux/tree/debug

My lib uses one JavaScript file which is imported by its d.ts (`src/proto/index.js`) which does not have any `require` or `import`. The only `require` are in `src/misc/polyfills` which are included in *karmaTypescriptConfig.bundlerOptions.exclude* of *karma.conf.js*. 
I am about to move from .js tests to .ts tests, but when running tests got this error:

```
19 09 2017 11:26:37.164:ERROR [karma]: TypeError: Cannot read property 'length' of undefined
    at Object.forEachChild (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:12301:70)
    at bindEachChild (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:18987:16)
    at bindChildrenWorker (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:19079:21)
    at bindChildren (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:18962:17)
    at bindContainer 
[karma_debug.txt](https://github.com/monounity/karma-typescript/files/1313717/karma_debug.txt)
(/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:18944:17)
    at bind (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:20195:21)
    at /home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:19693:17
    at visitNode (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:11900:24)
    at Object.forEachChild (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:12298:25)
    at bindJSDocTypedefTag (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:19686:16)
    at bindChildrenWorker (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:19076:21)
    at bindChildren (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:18962:17)
    at bind (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:20192:21)
    at bindJSDocTypedefTagIfAny (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:20218:25)
    at bind (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:20170:17)
    at bindEach (/home/philippe/workspace/netflux/node_modules/typescript/lib/typescript.js:18979:21)
```

Here is a peace of *karma.conf.js* file:
```javascript

basePath: '',

frameworks: ['jasmine', 'karma-typescript'],

files: [
    { pattern: 'src/**/*.+(js|ts)', included: false, served: false },
    'test/functional/1peer.test.ts',
    'test/util/helper.ts'
],

exclude: ['src/types/esdoc.helper.ts'],

preprocessors: {
    'test/**/*.+(js|ts)': ['karma-typescript']
},

karmaTypescriptConfig: {
  compilerOptions: {
      module: 'CommonJS',
      target: 'ES5',
      lib: [ 'es2017', 'dom' ],
      moduleResolution: 'node',
      downlevelIteration: true,
      sourceMap: true,
          types: ['node', 'text-encoding'],
          allowJs: true
      },
      bundlerOptions: {
          addNodeGlobals: false,
          exclude: ['wrtc', 'text-encoding', 'uws', 'node-webcrypto-ossl']
      }
},
```

And here is *tsconfig.json*:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    "lib": [ "es2017", "dom" ],
    "moduleResolution": "node",
    "downlevelIteration": true,
    "types": ["node", "text-encoding"]
  },
  "include": [
    "src/**/*",
    "test/**/*.ts"
  ],
  "exclude": ["**/*types/esdoc.helper.ts"]
}
```

I have tried different configuration mix, but was not able to find why this error. Could you help please?

**Comment by kalitine** [comment]
This might be a compilation problem with Typescript and not `karma-typescript`, as it does not compile with `tsc` command. I use RollupJS and it works, so that why I did not pay attention to `tsc`. Anyway if you have any idea it very appreciated, but actually it is not an issue with karma-typescript.

**Comment by erikbarke** [comment]
It seems that Typescript chokes on `src/proto/index.js`, I haven't found anything else 😕

**Comment by kalitine** [comment]
Thank you for the look. Indeed something goes wrong with `src/proto/index.js`. This file is generated by [protobufjs](https://github.com/dcodeIO/protobuf.js) lib and then bundled with Rollup using rollup-plugin-babel. However tests pass well.

Anyway I tried with TypeScript 2.4.2 and it works now. Thanks again and karma-typescript is really awesome!
