### ISSUE TITLE
3.0.6 causes karma to fail

### ISSUE THREAD

**Issue by rolandjitsu** [monounity/karma-typescript#185]
After I updated to latest version, I'm getting:
```text
> @bbpviz/utils@0.11.0 lint /Users/agroza/Projects/@bbpviz/utils
> tslint -c tslint.json -p ./src/tsconfig.spec.json -t stylish --type-check


> @bbpviz/utils@0.11.0 test /Users/agroza/Projects/@bbpviz/utils
> karma start karma.conf.js --browsers Chrome --single-run --log-level error

20 09 2017 13:19:15.682:ERROR [karma]: Error: property %s already exists on the sourcemap, use set property instead
    at Converter.addProperty (/Users/agroza/Projects/@bbpviz/utils/node_modules/convert-source-map/index.js:76:49)
    at SourceMap.createInlineSourceMap (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/bundler/source-map.js:21:18)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/bundler/bundler.js:56:120
    at Array.forEach (native)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/bundler/bundler.js:55:31
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/bundler/transformer.js:16:17
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Going back to `3.0.5` works.

**Comment by erikbarke** [comment]
This should be fixed now, does it work for you if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by rolandjitsu** [comment]
@erikbarke I think it's working now. I'm getting a different error, but let me check if it works after I fix it.

**Comment by rolandjitsu** [comment]
It seems to be working now.

Off topic, I've just setup a package that uses this plugin for testing TS code, but it seems to complain with:
```text
21 09 2017 18:21:51.311:ERROR [karma]: Error: Invalid syntax in bundle: 'import' and 'export' may only appear at the top level (4561:0)
in /var/folders/79/h3v4lxms63l65w8vx6qznlf80000gn/T/karma-typescript-bundle-95401CPnpsR417vaA.js
at line 4561, column 0:

... import { Injectable } from '@angular/core';
impor ...

Possible fix: configure karma-typescript to compile es6 modules with karma-typescript-es6-transform

    at Validator.validate (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/dist/bundler/validator.js:20:23)
    at Bundler.writeMainBundleFile (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/dist/bundler/bundler.js:173:24)
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/dist/bundler/bundler.js:109:19
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:421:16
    at replenish (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:931:17)
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:906:16
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/dist/bundler/globals.js:25:17
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:421:16
    at replenish (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:941:25)
    at iterateeCallback (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:931:17)
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:906:16
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/dist/bundler/globals.js:20:21
    at onDependenciesResolved (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:70:20)
    at /Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/rolandjitsu/Projects/infarm/core-app/node_modules/karma-typescript/node_modules/async/dist/async.js:998:13)
```

But it's strange, because I have a similar setup which doesn't use `karma-typescript-es6-transform`, but it works just fine.

**Comment by erikbarke** [comment]
My guess is one of your dependencies (or a sub dependency) in your project has been upgraded to a newer version which now uses the es6 syntax, which would explain the different behavior between two seemingly identical projects, just a guess. If you look inside the temp bundle file you'll find the culprit ☺️

Anyway, I'm closing this issue now and I'm releasing a hotfix this week!
