### ISSUE TITLE
Compiler do not compile files, but they are "processed" by preprocessor

### ISSUE THREAD

**Issue by l0nley** [monounity/karma-typescript#19]
Hi!
I have an issue. In general- typescript does not compile files, but they are found by preprocessor:
````

d
31 10 2016 15:03:00.763:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-firefox-launcher.                                                         
31 10 2016 15:03:00.767:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-jasmine.                                                                  
31 10 2016 15:03:00.770:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-junit-reporter.                                                           
31 10 2016 15:03:00.800:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-phantomjs-launcher.                                                       
31 10 2016 15:03:00.808:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-teamcity-reporter.                                                        
31 10 2016 15:03:00.810:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-threshold-reporter.                                                       
31 10 2016 15:03:00.943:DEBUG [plugin]: Loading plugin D:\Projects\TaiJi\Code\web-check-box\node_modules/karma-typescript.                                                               
31 10 2016 15:03:01.256:DEBUG [framework.karma-typescript]: Fallback to default compiler options:  { emitDecoratorMetadata: true,                                                        
  experimentalDecorators: true,                                                                                                                                                          
  jsx: 'react',                                                                                                                                                                          
  module: 'commonjs',                                                                                                                                                                    
  sourceMap: true,                                                                                                                                                                       
  target: 'ES5' }                                                                                                                                                                        
31 10 2016 15:03:01.261:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.0.6                                                                                       
31 10 2016 15:03:01.274:DEBUG [web-server]: Instantiating middleware                                                                                                                     
31 10 2016 15:03:01.286:DEBUG [reporter]: Trying to load reporter: karma-typescript                                                                                                      
31 10 2016 15:03:01.288:DEBUG [reporter]: Trying to load color-version of reporter: karma-typescript (karma-typescript_color)                                                            
31 10 2016 15:03:01.289:DEBUG [reporter]: Couldn't load color-version.                                                                                                                   
31 10 2016 15:03:01.310:DEBUG [preprocessor.karma-typescript]: Processing "D:/Projects/TaiJi/Code/web-check-box/src/check-box.module.ts".                                                
31 10 2016 15:03:01.312:DEBUG [preprocessor.karma-typescript]: Processing "D:/Projects/TaiJi/Code/web-check-box/src/check-box.component.ts".                                             
31 10 2016 15:03:01.312:DEBUG [preprocessor.karma-typescript]: Processing "D:/Projects/TaiJi/Code/web-check-box/src/check-box.controller.ts".                                            
31 10 2016 15:03:01.313:DEBUG [preprocessor.karma-typescript]: Processing "D:/Projects/TaiJi/Code/web-check-box/src/core.ts".                                                            
31 10 2016 15:03:01.315:DEBUG [preprocessor.karma-typescript]: Processing "D:/Projects/TaiJi/Code/web-check-box/src/test/core.spec.ts".                                                  
31 10 2016 15:03:01.823:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/angular/index.d.ts                                          
31 10 2016 15:03:01.829:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/jquery/index.d.ts                                           
31 10 2016 15:03:01.838:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/es6-shim/index.d.ts                                         
31 10 2016 15:03:01.840:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/jasmine/index.d.ts                                          
31 10 2016 15:03:01.843:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/node/index.d.ts                                             
31 10 2016 15:03:01.892:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/q/index.d.ts                                                
31 10 2016 15:03:01.894:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/@types/selenium-webdriver/index.d.ts                               
31 10 2016 15:03:01.908:DEBUG [compiler.karma-typescript]: Reading: D:/Projects/TaiJi/Code/web-check-box/node_modules/typescript/lib/lib.d.ts                                            
31 10 2016 15:03:02.992:INFO [compiler.karma-typescript]: Compiled 0 files in 1176 ms.                                                                                                   
[15:03:02] 'test' errored after 2.44 s                                                                                                                                                   
[15:03:02] Error: No source found for D:/Projects/TaiJi/Code/web-check-box/src/check-box.module.ts!                                                                                      
Is there a mismatch between the Typescript compiler options and the Karma config?                                                                                                        
    at D:\Projects\TaiJi\Code\web-check-box\node_modules\karma-typescript\lib\compiler.js:72:23                                                                                          
    at Array.forEach (native)                                                                                                                                                            
    at D:\Projects\TaiJi\Code\web-check-box\node_modules\karma-typescript\lib\compiler.js:66:19                  
                                                                                      
````
As i can understand, compiler do not perform compilation for files. There is my karma.conf.js
````
module.exports = function(config) {

    /*https://karma-runner.github.io/1.0/config/configuration-file.html*/

    var buildConfig = require('./build.config.js');

    config.set({
        basePath: buildConfig.component_dir,
        files: [
            'node_modules/angular/angular.js',
            'node_modules/angular-mocks/angular-mocks.js',
            'src/**/*.ts',
        ],
        logLevel: config.LOG_DEBUG,
        reporters: ['progress','karma-typescript'],
        frameworks: ['jasmine', 'karma-typescript'],
        preprocessors: {
            '**/*.ts' : ['karma-typescript'],
        },
        karmaTypescriptConfig: {
            reports: {
                'html' :'coverage',
                'text-summary': ''
            },
            compilerOptions: {
                emitDecoratorMetadata: true,
                experimentalDecorators: true,
                jsx: "react",
                noImplicitAny: true,
                module: "commonjs",
                sourceMap: true,
                target: "ES5",
            },
            excludeFromCoverage: /\.(d|spec|test)\.ts/
        },
              browserNoActivityTimeout: 40000,
        port: 9200,
        runnerPort: 9300,
        urlRoot: '/',
        singleRun: true,
        autoWatch: false,
        browsers: [
            'PhantomJS'
        ]
    });

};
````

I am totally lost, trying to investigate it. It looks like tsc host requires some options. I am using 
````
 "karma-typescript": "git://github.com/monounity/karma-typescript.git#2.1"
````
in my devDependencies. What is going in a wrong way here?

**Comment by l0nley** [comment]
It looks like tsconfig.fileNames never populated with values in compiler.js

**Comment by monounity** [comment]
@l0nley, adding files to tsconfig.fileNames on every compile makes the file list grow with duplicates, I'm not sure this is the way to go...

The framework tries to find files to compile in the following order:

* Look for a tsconfig path in the karmaTypescriptConfig
* Use the karma config `basePath` as the root to start looking for files

You don't have a path to your tsconfig in the karmaTypescriptConfig, but you're setting the karma basePath using `buildConfig.component_dir`, is that path the actual root of the project?

If you can't set `buildConfig.component_dir` to a root for Typescript  to list files for compilation, could you try pointing to your tsconfig from the `karma-typescript`config?

```javascript
karmaTypescriptConfig: {
    tsconfig: "path/to/your/tsconfig.json",
    compilerOptions: {
        module: "commonjs",
        sourceMap: true,
        target: "ES5"
        //... etc
    }
}
```

If that doesn't work, could you create a new PR with an integration test that reproduces the error?

**Comment by l0nley** [comment]
Well, I don't want to use tsconfig at all, because buildConfig.component_dir is not something static - it variable, which is set during build pipeline execution. In case I will need something to change in tsconfig, I need to generate this file, save somewhere and than resolve in karma.conf. It is not something i expected to do. I tried to use 
````
 karmaTypescriptConfig: {
           ...
            compilerOptions: {
                rootDir: buildConfig.component_dir +'\\src'
            },
            ....
        }
````
but unfortunately it does not work.  I think this is because 
````
-rootDir 	string 	(common root directory is computed from the list of input files) 	Specifies the root directory of input files. Only use to control the output directory structure with --outDir.
```` 
Since it is pipeline, i don't want to have ourDir to be defined. So root cause here, that you are not specifying source files explicitly. But why?
About growing tsconfig.fileNames - it can be prevented 
````
emitQueue.forEach(function(item) {
            if(tsconfig.fileNames.indexOf(item.file.originalPath) == -1) {
                tsconfig.fileNames.push(item.file.originalPath);
            }
        })
````
PR will be updated with this solution

**Comment by l0nley** [comment]
PR #21 updated:
In case tsconfig specified, then tsconfig.fileNames will not be populated. 
And in case it is not specified, fileNames will be populated only if corresponding filename not in array.

**Comment by monounity** [comment]
@l0nley, great! Could you also add an integration test to this PR that fails without your fix and passes with your fix? I'm thinking this would need a separate integration test suite, you could copy the example project and use that as a starting point. The 2.1 branch is still moving quite a lot, and your fix adds a third step in the file discovery mechanism, and I want to be able to refactor and move stuff around without being afraid of introducing regression bugs.

**Comment by monounity** [comment]
@l0nley, would this work for you?

There's a new configuration option now which allows you to exclude/include files/patterns in the karma.conf.js:

```javascript
karmaTypescriptConfig: {
    compilerOptions: {
        //...
    }
    include: ["**/*.ts"],
    exclude: ["foo"]
}
```

**Comment by l0nley** [comment]
Wow! This did the trick for me with absolute paths in include! Thanks man!
Only one comment: I was need to convert windows slashes in a path:
````
 var ptd = buildConfig.component_dir.replace(/\\/g,'/');
...
include: [ptd+'src/**/*.ts']
...  
````
I am not sure you actually need to convert path somewhere inside library, but, just to let you know.
Man, i really need this thing. When you plan to release?

**Comment by monounity** [comment]
@l0nley, glad we could work it out :) Your fix for windows slashes sounds like it belongs in lib/framework.js, where excludes and includes are extended, could you update your PR with your fix? No new integration tests needed, just the fix will do.

I'm still working out some issues with using the browserify tool chain for module loading, and after that I have to update the documentation, so the first beta release shouldn't be too far away!
