### ISSUE TITLE
3.0.9 broke NodeJS 5 support, was working fine in 3.0.8

### ISSUE THREAD

**Issue by lanthaler** [monounity/karma-typescript#230]
The 3.0.9 release broke NodeJS 5 support.

```
> karma start --single-run

03 01 2018 20:31:47.094:ERROR [plugin]: Error during loading "/home/travis/build/HydraCG/Heracles.ts/node_modules/karma-typescript" plugin:
  Invalid left-hand side in assignment
03 01 2018 20:31:47.105:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
  Perhaps you are missing some plugin?

/home/travis/build/HydraCG/Heracles.ts/node_modules/di/lib/injector.js:22
    return new Error(stack ? msg + ' (Resolving: ' + stack + ')' : msg);
           ^
Error: No provider for "framework:karma-typescript"! (Resolving: framework:karma-typescript)
    at error (/home/travis/build/HydraCG/Heracles.ts/node_modules/di/lib/injector.js:22:12)
    at Object.parent.get (/home/travis/build/HydraCG/Heracles.ts/node_modules/di/lib/injector.js:9:13)
    at null.get (/home/travis/build/HydraCG/Heracles.ts/node_modules/di/lib/injector.js:54:19)
    at /home/travis/build/HydraCG/Heracles.ts/node_modules/karma/lib/server.js:143:20
    at Array.forEach (native)
    at null.Server._start (/home/travis/build/HydraCG/Heracles.ts/node_modules/karma/lib/server.js:142:21)
    at null.invoke (/home/travis/build/HydraCG/Heracles.ts/node_modules/di/lib/injector.js:75:15)
    at null.Server.start (/home/travis/build/HydraCG/Heracles.ts/node_modules/karma/lib/server.js:103:18)
    at Object.exports.run (/home/travis/build/HydraCG/Heracles.ts/node_modules/karma/lib/cli.js:280:26)
    at Object.<anonymous> (/home/travis/build/HydraCG/Heracles.ts/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
```

See this TravisCI run e.g. https://travis-ci.org/HydraCG/Heracles.ts/jobs/324737590

Here's is a run of the same tests with karma-typescript fixed to 3.0.8: https://travis-ci.org/HydraCG/Heracles.ts/jobs/324741313

**Comment by erikbarke** [comment]
Ok, this happens because the package `pad` was upgraded to ^2.0.0, it uses CoffeScript 2 which outputs ES6 syntax which [isn't fully available in Node.js 5.12](http://node.green/).

The breaking commit is here: https://github.com/adaltas/node-pad/commit/134087510827b75d933a3311bac2d651b54d4cd4#diff-6d186b954a58d5bb740f73d84fe39073

It works if I downgrade manually to `pad@1.2.1` 😞
