### ISSUE TITLE
source-map dependency >=0.5.6 --> 0.7.0 breaks 

### ISSUE THREAD

**Issue by niels1voo** [monounity/karma-typescript#240]
![image](https://user-images.githubusercontent.com/223998/35188925-fcf04352-fe0d-11e7-915d-c92bb453ca30.png)

![image](https://user-images.githubusercontent.com/223998/35188928-283ac2ee-fe0e-11e7-9275-3cc73960678d.png)

source-map 0.7.0 was released yesterday, which has a breaking change for k-t as far as i can tell.  can you pin the version at 0.6.1 until you have time to fix?

**Comment by niels1voo** [comment]
this may primarily be a remap-instanbul problem
https://github.com/SitePen/remap-istanbul/issues/160

**Comment by jukibom** [comment]
can I just leave `TypeError: sourceMap.originalPositionFor is not a function` for people coming from google? 

Thank you for the PR!

**Comment by rolandjitsu** [comment]
I'm actually getting new errors now:
```plain
Error: Could not find source map for: "/Users/agroza/Projects/@bbpviz/utils/src/lib/browser/event-listener.ts"
    at CoverageTransformer.addFileCoverage (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:171:18)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:298:14
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addCoverage (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/CoverageTransformer.js:296:24)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/remap.js:51:13
    at Array.forEach (<anonymous>)
    at Reporter.remap (/Users/agroza/Projects/@bbpviz/utils/node_modules/remap-istanbul/lib/remap.js:50:16)
    at /Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/karma/reporter.js:38:42
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma/lib/browser_collection.js:93:21)
    at Reporter.create.onRunComplete (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma-typescript/dist/karma/reporter.js:26:26)
    at Server.<anonymous> (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:130:20)
    at Server.emit (events.js:213:7)
    at emitRunCompleteIfAllBrowsersDone (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma/lib/server.js:336:12)
    at Server.<anonymous> (/Users/agroza/Projects/@bbpviz/utils/node_modules/karma/lib/server.js:367:7)
Error: Could not find source map for: "/Users/agroza/Projects/@bbpviz/utils/src/lib/browser/resolution.ts"
```

**Comment by erikbarke** [comment]
Locking to `source-map@0.6.1` didn't work in some environments where older versions of `remap-istanbul` would pull in `source-map@0.7.0` regardless of what's in the package.json of `karma-typescript`, so I'm working on a proper upgrade to the latest `remap-istanbul`  in #245 and #246 now!
