### ISSUE TITLE
Build fails when bundlerOptions.sourceMap is true for files in node_modules

### ISSUE THREAD

**Issue by rmja** [monounity/karma-typescript#241]
Repro: https://github.com/rmja/karma-error
Run `npm run test`

It executes correctly when `bundlerOptions.sourceMap = false`, but raises the following error when `bundlerOptions.sourceMap = true`:

![image](https://user-images.githubusercontent.com/2112306/35330882-7f420e04-0105-11e8-9c78-41cbe3abf3e2.png)

The `Reflect.ts` file clearly does not exist.

**Comment by rmja** [comment]
One more thing, the test also runs if the `import 'reflect-metadata';` line is removed from `hello.spec.ts`. The reason I need it here is to polyfill before the test execution.

**Comment by erikbarke** [comment]
This is a known issue in reflect-metadata@0.1.12, https://github.com/rbuckton/reflect-metadata/issues/87, your test project works if I downgrade to 0.1.10...

**Comment by rmja** [comment]
Ahh yes, I did not check that. Do you plan to handle this gracefully since you marked it as a bug?

**Comment by erikbarke** [comment]
Yes, there's a fix in #242, does it work on your end too?

**Comment by rolandjitsu** [comment]
Could this be related to https://github.com/SitePen/remap-istanbul/issues/162? I'm having a similar issue.

**Comment by rolandjitsu** [comment]
Ok, no. This is a different issue actually. I get:
```
26 01 2018 16:00:35.991:ERROR [karma]: TypeError: sourceMap.originalPositionFor is not a function
    at getMapping (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/getMapping.js:27:26)
    at getMappingResolved (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/CoverageTransformer.js:204:46)
    at remapBranch (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/remapBranch.js:14:19)
    at /Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/CoverageTransformer.js:214:44
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addFileCoverage (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/CoverageTransformer.js:210:42)
    at /Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/CoverageTransformer.js:268:14
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addCoverage (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/CoverageTransformer.js:266:24)
    at /Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/remap.js:48:13
    at Array.forEach (<anonymous>)
    at Reporter.remap (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/node_modules/remap-istanbul/lib/remap.js:47:16)
    at /Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/dist/karma/reporter.js:38:42
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma/lib/browser_collection.js:93:21)
    at Reporter.create.onRunComplete (/Users/agroza/Projects/@bbpviz/three-trackball-controls/node_modules/karma-typescript/dist/karma/reporter.js:26:26)
npm ERR! code ELIFECYCLE
```

**Comment by erikbarke** [comment]
@rolandjitsu, the `sourceMap.originalPositionFor` error is tracked in #240!

**Comment by rmja** [comment]
@erikbarke yes, I can confirm that downgrading reflect-metadata to 0.1.10 resolves the issue, and I can also confirm that the fix in the `handle-broken-sourcemaps` branch fixes the issue when the newer reflect-metadata version is used.
