### ISSUE TITLE
Error with custom index.d.ts

### ISSUE THREAD

**Issue by DariuszOstolski** [monounity/karma-typescript#254]
Hello,
I'm not sure whether it is a bug or something wrong with my configuration. I've got an index.d.ts file for ipaddr.js library: https://github.com/whitequark/ipaddr.js/blob/master/README.md
Those are contents of this file:
```

/// <reference types="node" />
/* tslint:disable */

declare module 'ipaddr.js' {

    interface IPv4 {
        kind(): string;

        toString(): string;

        toNormalizedString(): string;

        toByteArray(): Array<number>;

        match(other: IPv4, cidrRange: any): boolean;

        range(): any;
    }

    interface IPv6 {
        kind(): string;

        toString(): string;

        toNormalizedString(): string;

        toByteArray(): Array<number>;

        range(): any;
    }

    var ipaddr: {
        isValid(str: string): boolean;

        parse(str: string): IPv4 | IPv6;
        parseCIDR(str: string): (any)[];
        fromByteArray(bytes: any[]): IPv4 | IPv6;
        process(str: string): IPv4 | IPv6;
    }

    export default ipaddr;
}


```
It is located in following directory:

```src/@types/ipaddr.js/index.d.ts```

In my tsconfig.ts I have following options:
```
"compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "declaration": true,
    "strict": true,
    "moduleResolution": "node",
    "module": "es2015",
    "target": "es2015",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "removeComments": false,
    "sourceMap": true,
    "outDir": "./dist",
    "lib": [
      "es2015",
      "dom"
    ],
    "typeRoots": [
      "@types",
      "./@types"
    ],
    "types": [
      "jasmine",
      "node"
    ]
  },
```

AOT build is fine but when I want to start unit tests under karma I have following error:

Chrome 63.0.3239 (Linux 0.0.0) ERROR
  ```
{
    "message": "Uncaught Error: Can't find ipaddr.js [undefined] (required by ...src/common/utils/ipv4-utility.ts)\nat node_modules/karma-typescript/src/client/commonjs.js:13:
```

I suspect it is because this index.d.ts file gets transpiled to something like that:
```
(function(global){global.wrappers['src/@types/ipaddr.js/index.d.ts']=[function(require,module,exports,__dirname,__filename){ undefined
},'src/@types/ipaddr.js/index.d.ts',{}];})(this);

```
So in fact it is undefined. Here is my karma.conf:

```module.exports = function (config) {
    config.set({

        frameworks: ["jasmine", "karma-typescript"],
        client: {
            builtPaths: ['src', 'testing'], // add more spec base paths as needed
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },


        files: [
            {pattern: "src/**/*.+(ts|html)"},
            {pattern: "testing/**/*.+(ts|html)"},

            // Polyfills
            'node_modules/core-js/client/shim.js',
            'node_modules/reflect-metadata/Reflect.js',

            // zone.js
            'node_modules/zone.js/dist/zone.js',
            'node_modules/zone.js/dist/long-stack-trace-zone.js',
            'node_modules/zone.js/dist/proxy.js',
            'node_modules/zone.js/dist/sync-test.js',
            'node_modules/zone.js/dist/jasmine-patch.js',
            'node_modules/zone.js/dist/async-test.js',
            'node_modules/zone.js/dist/fake-async-test.js',
            'node_modules/ipaddr.js/lib/ipaddr.js',

            // RxJs
            {pattern: 'node_modules/rxjs/**/*.js', included: false, watched: false},
            {pattern: 'node_modules/rxjs/**/*.js.map', included: false, watched: false},

            //primeng
            {pattern: 'node_modules/primeng/**/*.js', included: false, watched: false},

            // Paths loaded via module imports:
            // Angular itself
            {pattern: 'node_modules/@angular/**/*.js', included: false, watched: false},
            {pattern: 'node_modules/@angular/**/*.js.map', included: false, watched: false}
        ],

        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },

        karmaTypescriptConfig: {
            bundlerOptions: {
                entrypoints: /\.spec\.ts$/,
                transforms: [
                    require("karma-typescript-angular2-transform")
                ],
                resolve: {
                    alias: {"ipaddr.js": "node_modules/ipaddr.js/lib/ipaddr.js"},  // module alias
                }
            },
            coverageOptions: {
                exclude: [/\.(d|test)\.ts$/i]
            },
            exclude: ["dist"],
            compilerOptions: {
                module: "commonjs"
            },
            tsconfig: "./tsconfig.json",

        },

        reporters: ["dots", "karma-typescript"],

        browsers: ["Chrome"]
    });
};
```

**Comment by mdvorscak** [comment]
I have a similar issue when using https://github.com/michealparks/document-ready-promise library. However, in my case this library + index.d was previously working on release 3.0.4. I however can't use this anymore since we are switching from npm to yarn and during the switch the resolution of the `remap-istanbul` library is different which causes another error (which is solved in latter versions of karma-typescript)

**Comment by erikbarke** [comment]
Hey guys, the file pattern `{pattern: "src/**/*.+(ts|html)"},` matches also .d.ts files in the src/@types folder, which are fed to the Typescript compiler which resolves them as [ambient modules](https://github.com/monounity/karma-typescript/tree/master/tests/integration-latest/src/bundling/ambient), which makes karma-typescript include them in the bundle.

The solution is simple;  you can either exclude the @types folder in the Karma config, `exclude: ["src/@types/**"]` or perhaps move the @types folder out of the src folder.

**Comment by mdvorscak** [comment]
Thanks so much, that fixed the issue!

**Comment by DariuszOstolski** [comment]
The file is no longer transpiled (after moving it to separate directory from src).

Unfortunately it does not work in my case:
```
23 02 2018 17:42:24.866:DEBUG [web-server]: serving (cached): /home/dostolski/gui/f8-ne-gui/f8-dcn-app/node_modules/karma-typescript/src/client/commonjs.js
Chrome 63.0.3239 (Linux 0.0.0) ERROR
  {
    "message": "Uncaught Error: Can't find ipaddr.js [undefined] (required by ...src/common/utils/ipv4-utility.ts)\nat node_modules/karma-typescript/src/client/commonjs.js:13:17\n\nError: Can't find ipaddr.js [undefined] (required by ..src/common/utils/ipv4-utility.ts)\n    at require (node_modules/karma-typescript/src/client/commonjs.js:13:23)\n    at node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at Object.global.wrappers .../src/common/utils/ipv4-utility.ts (src/common/utils/ipv4-utility.ts:1:0 <- src/common/utils/ipv4-utility.js:20:33)\n    at require (node_modules/karma-typescript/src/client/commonjs.js:17:25)\n    at node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at Object.global.wrappers...../src/common/f8-common.module.ts.@angular/core (src/common/f8-common.module.ts:101:0 <- src/common/f8-common.module.js:205:34)\n    at require (node_modules/karma-typescript/src/client/commonjs.js:17:25)\n    at node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at 
```
When I debug I see that it is actually undefined in this function:
```
 function require(filename, requiring, required) {
        var wrapper,
            module = global.__karmaTypescriptModules__ [filename];
        if (!module) {
            wrapper = global.wrappers[filename];
            if(!wrapper) {
                throw new Error("Can't find " + required + " [" + filename + "] (required by " + requiring + ")");
            }
            module = { exports: {}, id: wrapper[id], uri: filename };
            global.__karmaTypescriptModules__ [filename] = module;
            wrapper[fn].call(module.exports, function (dependency) {
                return require(wrapper[map][dependency], filename, dependency);
            }, module, module.exports, filename.slice(0, filename.lastIndexOf("/")), filename);
            if(module.exports && !module.exports.default && isExtensible(module.exports)) {
                Object.defineProperty(module.exports, "default", {
                    enumerable: false, configurable: true, writable: true, value: module.exports
                });
            }
        }
        return module.exports;
    }
```

**Comment by erikbarke** [comment]
Excluding it (`exclude: ["src/@types/**"]`) worked for me, have you tried that?

**Comment by DariuszOstolski** [comment]
Hello,

I have tried that but it didnt work for me because I have  "noImplicitAny": set to true and then I had error with import statement.  I  move it to separate directory, no import errors during compilation, but at runtime it cannot be loaded. Although when I open debug and check the sources I see that library is present
![ipaddr](https://user-images.githubusercontent.com/4119217/36660986-41d1c4da-1ada-11e8-805b-d4957e5647ff.png)

**Comment by erikbarke** [comment]
Could you make a small repo that reproduces this that I could take a look at?

**Comment by DariuszOstolski** [comment]
Sure, I'll try to provide you a repro.

**Comment by DariuszOstolski** [comment]
As I tried to provide You a github repo to be able to reproduce a problem I found a problem in my tsconfig file and was able to fix it.
Basically the issue was "ipaddr.js" was missing in types section:

```
"typeRoots": [
      "./@types",
      "./node_modules/@types"
    ],
    "types": [
      "jasmine",
      "node",
      "angular",
      "karma",
      "lodash",
      "ipaddr.js"
    ]
```
So I think issue can be closed.
