### ISSUE TITLE
Path mappings are not resolved

### ISSUE THREAD

**Issue by rolandjitsu** [monounity/karma-typescript#261]
It seems like path mappings are not resolved as expected. I've got the following `tsconfig.json`:
```json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "baseUrl": ".",
        "module": "commonjs",
        "target": "es5",
        "outDir": "./lib",
        "types": [
            "jasmine",
            "node"
        ],
        "paths": {
            "@gvt/utils": [
                "../utils/src"
            ]
        }
    },
    "include": [
        "test/setup.ts",
        "**/*.spec.ts",
        "src/**/*.ts"
    ]
}
```

And karma config:
```js
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

const {resolve} = require('path');
const nodeModules = resolve('../',  '../','node_modules');

const chromeFlags = [
    // IMPORTANT: --no-sandbox is a required flag for running Chrome in unprivileged Docker containers,
    // see https://github.com/karma-runner/karma-chrome-launcher/issues/125#issuecomment-312668593
    '--no-sandbox',
    '--headless',
    '--disable-gpu'
];

module.exports = function (config) {
    config.set({
        basePath: '',
        frameworks: [
            'jasmine',
            'karma-typescript'
        ],
        reporters: ['spec', 'karma-typescript'],
        preprocessors: {
            '**/*.ts': ['karma-typescript']
        },
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-spec-reporter'),
            require('karma-typescript')
        ],
        files: [
            // ES6/ES7 shims
            `${nodeModules}/core-js/client/shim.min.js`,
            {pattern: `${nodeModules}/core-js/client/shim.min.js.map`, included: false, served: true},
            // `${nodeModules}/reflect-metadata/Reflect.js`,
            // Setup Angular test env
            {pattern: 'test/setup.ts'},
            // Specs
            {pattern: 'src/**/*.ts'}
        ],
        karmaTypescriptConfig: {
            tsconfig: './tsconfig.spec.json',
            bundlerOptions: {
                entrypoints: /test\.ts|\.spec\.ts$/,
                transforms: []
            },
            coverageOptions: {
                exclude: /\.(d|spec|test)\.ts|src\/index\.ts$/i,
                threshold: {
                    global: {
                        statements: 75,
                        branches: 60,
                        functions: 70,
                        lines: 80
                    }
                }
            },
            reports: {
                html: '.coverage',
                'text-summary': ''
            }
        },
        coverageReporter: {
            instrumenterOptions: {
                istanbul: {noCompact: true}
            }
        },
        logLevel: config.LOG_INFO,
        browsers: ['Chrome'],
        customLaunchers: {
            CHROMIUM_HEADLESS: {
                base: 'ChromiumHeadless',
                flags: chromeFlags
            },
            CHROME_HEADLESS: {
                base: 'Chrome',
                flags: [
                    ...chromeFlags,
                    '--remote-debugging-port=9000'
                ]
            }
        }
    });
};
```

But when running karma, it fails with:
```json
{
    "message": "Uncaught Error: Can't find @gvt/utils [/Users/rolandjitsu/Projects/gvatravel/frontend/packages/utils/src/index.ts] (required by /Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.ts)\nat /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:13:17\n\nError: Can't find @gvt/utils [/Users/rolandjitsu/Projects/gvatravel/frontend/packages/utils/src/index.ts] (required by /Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.ts)\n    at require (/Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:13:23)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at Object.global.wrappers./Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.ts.tslib (src/directive.ts:2:0 <- src/directive.js:24:27)\n    at require (/Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:17:25)\n  at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at Object.global.wrappers./Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.spec.ts.tslib (src/directive.spec.ts:1:0 <- src/directive.spec.js:3:19)\n    at require (/Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:17:25)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:32:9\n    at Array.forEach (<anonymous>)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:31:40",
    "str": "Uncaught Error: Can't find @gvt/utils [/Users/rolandjitsu/Projects/gvatravel/frontend/packages/utils/src/index.ts] (required by /Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.ts)\nat /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:13:17\n\nError: Can't find @gvt/utils [/Users/rolandjitsu/Projects/gvatravel/frontend/packages/utils/src/index.ts] (required by /Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.ts)\n    at require (/Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:13:23)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at Object.global.wrappers./Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.ts.tslib (src/directive.ts:2:0 <- src/directive.js:24:27)\n    at require (/Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:17:25)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:18:24\n    at Object.global.wrappers./Users/rolandjitsu/Projects/gvatravel/frontend/packages/testing/src/directive.spec.ts.tslib (src/directive.spec.ts:1:0 <- src/directive.spec.js:3:19)\n    at require (/Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:17:25)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:32:9\n    at Array.forEach (<anonymous>)\n    at /Users/rolandjitsu/Projects/gvatravel/frontend/node_modules/karma-typescript/src/client/commonjs.js:31:40"
  }
```

If I run `tsc` with the same config, it finds the referenced module.

Note that I'm inside a yarn workspace.

I'm using the latest version: `3.0.12`.

**Comment by erikbarke** [comment]
Do you have an example repo I could take a look at?

**Comment by rolandjitsu** [comment]
@erikbarke not really. But I'll try to setup one if you don't find the cause of the issue.

**Comment by erikbarke** [comment]
It would be tremendously helpful, over time these kinds of issues have proven almost impossible to reproduce without an example repo 😞

**Comment by gabrielbiga** [comment]
I think its a bug. Same issue here with a simple Yarn Workspace project...

**Comment by erikbarke** [comment]
@rolandjitsu, @gabrielbiga, does anyone of you guys have an example repo I could take a look at?

**Comment by rolandjitsu** [comment]
@erikbarke I never got around to do it.

I think I got passed this error at the time but got into another where tests would just hang and never run and at that point I decided to switch to jest + ts-jest which worked much better (with the drawback that I run tests headless using jsdom).

**Comment by houfu** [comment]
I wanna help with a repo: https://github.com/houfu/kts-issue-261. Hope this helps.

Error message as follows.
```
> kts-issue-261@1.0.0 test /Users/houfuang/WebstormProjects/kts-issue-261
> karma start

10 11 2018 19:43:48.591:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.1.6
10 11 2018 19:43:49.740:INFO [compiler.karma-typescript]: Compiled 3 files in 1129 ms.
10 11 2018 19:43:50.333:INFO [bundler.karma-typescript]: Bundled imports for 1 file(s) in 88 ms.
10 11 2018 19:43:50.334:WARN [karma]: No captured browser, open http://localhost:9876/
10 11 2018 19:43:50.338:INFO [karma-server]: Karma v3.1.1 server started at http://0.0.0.0:9876/
10 11 2018 19:43:50.338:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
10 11 2018 19:43:50.344:INFO [launcher]: Starting browser ChromeHeadless
10 11 2018 19:43:50.980:INFO [HeadlessChrome 0.0.0 (Mac OS X 10.14.1)]: Connected on socket rkln6te39Jzy-ZWHAAAA with id 72693442
HeadlessChrome 0.0.0 (Mac OS X 10.14.1): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
HeadlessChrome 0.0.0 (Mac OS X 10.14.1) ERROR
  {
    "message": "An error was thrown in afterAll\nUncaught Error: Can't find @test/main [/Users/houfuang/WebstormProjects/kts-issue-261/test_dir/main.ts] (required by /Users/houfuang/WebstormProjects/kts-issue-261/main.spec.ts)",
    "str": "An error was thrown in afterAll\nUncaught Error: Can't find @test/main [/Users/houfuang/WebstormProjects/kts-issue-261/test_dir/main.ts] (required by /Users/houfuang/WebstormProjects/kts-issue-261/main.spec.ts)"
  }
HeadlessChrome 0.0.0 (Mac OS X 10.14.1): Executed 0 of 0 ERROR (0 secs / 0 secs)
HeadlessChrome 0.0.0 (Mac OS X 10.14.1): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
```

**Comment by gitowiec** [comment]
I have the same issue, I am on monorepo and here is my karma.config.js
```
const path = require('path');
const tsConfig = require('./tsconfig');


module.exports = function (config) {
  let basePath = path.resolve('./');
  console.log({basePath});

  config.set({
    autoWatch: true,
    singleRun: true,

    basePath: basePath,
    browsers: ['PhantomJS'],
    logLevel: config.LOG_ERROR,

    frameworks: ['karma-typescript', 'mocha', 'chai', 'sinon'],

    files: [
      './src/**/*-test.ts',
    ],

    preprocessors: {
      'src/**/*-test.ts': ['karma-typescript', 'sourcemap'],
    },

    reporters: ['mocha'],

    karmaTypescriptConfig: {
      bundlerOptions: {
        transforms: [require('karma-typescript-es6-transform')()],
      },
      compilerOptions: {
        ...tsConfig.compilerOptions,
        strictNullChecks: false,
      },
    },

    junitReporter: {
      useBrowserName: true,
      outputDir: './test-results/',
    },
  });
};

```

**Comment by brizental** [comment]
Hey folks, I am having the same issue here.
 
My fix for now was to set aliases like this:

```js
karmaTypescriptConfig: {
  tsconfig: "tsconfig.json",
  bundlerOptions: {
    resolve: {
      alias: { ...aliases here... }
    }
  }
}
```

This is of course not ideal, the paths are defined in the `tsconfig.json` and should be picked up from there. 

Since this issue has not seen any action in a while, would someone mind confirming that this is still an issue for which help is wanted? I am happy to send a PR. Pointers welcome :)
