### ISSUE TITLE
Can't find source map for externally compiled files.

### ISSUE THREAD

**Issue by jamesots** [monounity/karma-typescript#272]
When some typescript has been compiled using tsc instead of
having karma-typescript compile it, karma-typescript fails to
find the source maps — it looks like the problem is in the readFile
method in reporter.ts, where the source file isn't found in
sharedProcessedFile.

I have created a test setup here to reproduce the problem:

https://github.com/jamesots/karma-ts-map-test

```
Error: Could not find source map for: "/home/james/dev/code/karma-ts-map-test/build/js/one.js"
    at CoverageTransformer.addFileCoverage (/home/james/dev/code/karma-ts-map-test/node_modules/remap-istanbul/src/CoverageTransformer.js:102:15)
    at /home/james/dev/code/karma-ts-map-test/node_modules/remap-istanbul/src/CoverageTransformer.js:238:10
    at Array.forEach (<anonymous>)
    at CoverageTransformer.addCoverage (/home/james/dev/code/karma-ts-map-test/node_modules/remap-istanbul/src/CoverageTransformer.js:236:5)
    at /home/james/dev/code/karma-ts-map-test/node_modules/remap-istanbul/src/remap.js:34:7
    at Array.forEach (<anonymous>)
    at Reporter.remap (/home/james/dev/code/karma-ts-map-test/node_modules/remap-istanbul/src/remap.js:33:11)
    at /home/james/dev/code/karma-ts-map-test/node_modules/karma-typescript/src/karma/reporter.ts:61:42
    at Array.forEach (<anonymous>)
    at BrowserCollection.forEach (/home/james/dev/code/karma-ts-map-test/node_modules/karma/lib/browser_collection.js:90:26)
    at Reporter.create.onRunComplete (/home/james/dev/code/karma-ts-map-test/node_modules/karma-typescript/src/karma/reporter.ts:45:26)
    at Server.<anonymous> (/home/james/dev/code/karma-ts-map-test/node_modules/karma/lib/events.js:39:26)
    at emitTwo (events.js:131:20)
    at Server.emit (events.js:214:7)
    at emitRunCompleteIfAllBrowsersDone (/home/james/dev/code/karma-ts-map-test/node_modules/karma/lib/server.js:256:14)
    at Server.<anonymous> (/home/james/dev/code/karma-ts-map-test/node_modules/karma/lib/server.js:285:9)
npm ERR! Test failed.  See above for more details.
```

**Comment by Nel75** [comment]
I'm currently working around this issue by specifying a **warn** option in the karma.conf.js. E.g.,

karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
        remapOptions: {
          warn: function(){}
        }
}

There's another undocumented option **warnMissingSourceMaps**, which would be better to just bypass these bogus errors instead of every warning, but it's not supported by the version of remap-istanbul  v0.10.1 currently bundled with the latest version of karma-typescript.

**Comment by erikbarke** [comment]
Closing in favor of #283.
