### ISSUE TITLE
Cannot find module ...

### ISSUE THREAD

**Issue by makamekm** [monounity/karma-typescript#276]
This package completely does not work...

karma.js
```
var path = require('path');

const host = process.argv[process.argv.length - 4];
const port = process.argv[process.argv.length - 3];
const portWS = process.argv[process.argv.length - 2];
const pattern = process.argv[process.argv.length - 1];

module.exports = (config) => {
    config.set({
        singleRun: true,
        frameworks: ['jasmine', 'karma-typescript'],
        reporters: ['progress', 'karma-typescript'],

        plugins: [
            require('karma-jasmine'),
            require('karma-typescript'),
            require('karma-chrome-launcher'),
        ],
        
        preprocessors: {
            '**/*.+(ts|tsx)': ['karma-typescript']
        },

        client: {
            port,
            host,
            portWS
        },

        files: [
            {
                pattern: `./src/Test/Component/${pattern}.test.+(ts|tsx)`,
                watched: false
            }
        ],

        logLevel: config.LOG_ERROR,

        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.karma.json",
            reports: {
                "cobertura": null,
                "html": null,
                "text-summary": null
            },
            bundlerOptions: {
                resolve: {
                    extensions: [".ts", ".tsx"],
                    directories: ["node_modules"]
                },
            }
        },
        
        browsers: ['ChromeHeadless'],
        port: 9876,

        customLaunchers: {
            ChromeHeadless: {
                base: 'Chrome',
                flags: [
                    '--headless',
                    '--disable-gpu',
                    '--no-sandbox',
                    '--remote-debugging-port=9222',
                    '--disable-web-security'
                ],
                debug: true
            }
        }
    })
}
```

Output:
```
reiso makame$ npm run test_client "127.0.0.1" 7878 6767 "Upload"

> reiso-src@0.2.14 test_client /Users/makame/reiso
> karma start karma.js -- "127.0.0.1" "7878" "6767" "Upload"

16 07 2018 00:36:26.127:ERROR [karma]: Error: Unable to resolve module [zen-observable] from [/Users/makame/reiso/node_modules/zen-observable-ts/lib/bundle.umd.js]
{
  "basedir": "/Users/makame/reiso",
  "extensions": [
    ".ts",
    ".tsx",
    ".ts",
    ".tsx"
  ],
  "moduleDirectory": [
    "node_modules"
  ],
  "modules": {
    "assert": "/Users/makame/reiso/node_modules/assert/assert.js",
    "buffer": "/Users/makame/reiso/node_modules/buffer/index.js",
    "child_process": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "cluster": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "console": "/Users/makame/reiso/node_modules/console-browserify/index.js",
    "constants": "/Users/makame/reiso/node_modules/constants-browserify/constants.json",
    "crypto": "/Users/makame/reiso/node_modules/crypto-browserify/index.js",
    "dgram": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "dns": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "domain": "/Users/makame/reiso/node_modules/domain-browser/source/index.js",
    "events": "/Users/makame/reiso/node_modules/events/events.js",
    "fs": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "http": "/Users/makame/reiso/node_modules/stream-http/index.js",
    "https": "/Users/makame/reiso/node_modules/https-browserify/index.js",
    "module": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "net": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "os": "/Users/makame/reiso/node_modules/os-browserify/browser.js",
    "path": "/Users/makame/reiso/node_modules/path-browserify/index.js",
    "punycode": "/Users/makame/reiso/node_modules/punycode/punycode.js",
    "querystring": "/Users/makame/reiso/node_modules/querystring-es3/index.js",
    "readline": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "repl": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "stream": "/Users/makame/reiso/node_modules/stream-browserify/index.js",
    "_stream_duplex": "/Users/makame/reiso/node_modules/karma-typescript/node_modules/readable-stream/duplex.js",
    "_stream_passthrough": "/Users/makame/reiso/node_modules/karma-typescript/node_modules/readable-stream/passthrough.js",
    "_stream_readable": "/Users/makame/reiso/node_modules/karma-typescript/node_modules/readable-stream/readable.js",
    "_stream_transform": "/Users/makame/reiso/node_modules/karma-typescript/node_modules/readable-stream/transform.js",
    "_stream_writable": "/Users/makame/reiso/node_modules/karma-typescript/node_modules/readable-stream/writable.js",
    "string_decoder": "/Users/makame/reiso/node_modules/karma-typescript/node_modules/string_decoder/lib/string_decoder.js",
    "sys": "/Users/makame/reiso/node_modules/util/util.js",
    "timers": "/Users/makame/reiso/node_modules/timers-browserify/main.js",
    "tls": "/Users/makame/reiso/node_modules/karma-typescript/dist/bundler/resolve/empty.js",
    "tty": "/Users/makame/reiso/node_modules/tty-browserify/index.js",
    "url": "/Users/makame/reiso/node_modules/url/url.js",
    "util": "/Users/makame/reiso/node_modules/util/util.js",
    "vm": "/Users/makame/reiso/node_modules/vm-browserify/index.js",
    "zlib": "/Users/makame/reiso/node_modules/browserify-zlib/lib/index.js",
    "_process": "/Users/makame/reiso/node_modules/process/browser.js"
  },
  "filename": "",
  "paths": []
}
Error: Cannot find module 'zen-observable' from '/Users/makame/reiso/node_modules/zen-observable-ts/lib'
    at /Users/makame/reiso/node_modules/karma-typescript/src/bundler/resolve/resolver.ts:194:27
    at /Users/makame/reiso/node_modules/browser-resolve/index.js:265:24
    at /Users/makame/reiso/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:14
    at process (/Users/makame/reiso/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/makame/reiso/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/makame/reiso/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/makame/reiso/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/makame/reiso/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

tsconfig.karma.json
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "esnext",
      "dom",
      "esnext.asynciterable"
    ],
    "importHelpers": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "jsx": "react",
    "typeRoots": [
      "node_modules/@types"
    ],
    "stripInternal": true,
    "skipLibCheck": true,
    "noLib": false,
    "declaration": true,
    "baseUrl": "./src",
    "outDir": "./build",
    "types": ["jasmine", "node"],
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowJs": false
  },
  "compileOnSave": false,
  "suppressImplicitAnyIndexErrors": true,
  "exclude": [
    "node_modules",
    "build",
    "composer.js",
    "example"
  ]
}
```

"zen-observable" is installed

**Comment by erikbarke** [comment]
Closing due to inactivity.
