### ISSUE TITLE
Support TS flag resolveJsonModule

### ISSUE THREAD

**Issue by vidartf** [monounity/karma-typescript#291]
In TS 2.9, a compiler flag [resolveJsonModule](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule) was added. Using this in my TS code, I get the following exception with karma-typescript:

Code:
```ts
import data from '../package.json';
```

Output:
```
<timestamp>:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.0.3
<timestamp>:ERROR [compiler.karma-typescript]: src/test(1,8): error TS1192: Module '"<abs folder dir>/package"' has no default export.
```

**Comment by vidartf** [comment]
I see that the activity on the repo has gone down quite a bit, so if possible I'd like to help contribute the fix as well. I'd need a little guiding though (there's no contributors guide):

From a quick glance at the code, I guess this means a change in https://github.com/monounity/karma-typescript/blob/master/src/bundler/bundle-item.ts ? I'm a little confused about where to add the changes though, and what the consequences of the different categories are.

**Comment by erikbarke** [comment]
Hey @vidartf, here are the [contributing guidelines](https://github.com/monounity/karma-typescript/wiki/Contributing)! This project is quite heavily integration tested, so as long as those tests don't break it's probably safe to add new stuff like this 😌The bundle-item class is probably a good place to start fiddling 🤔

**Comment by vidartf** [comment]
Actually, just cloning the repo and installing with the CI script, the tests fail for me (Windows 10, node 8.9.1, npm 6.4.0). A little daunting to go fiddling then.

**Comment by vidartf** [comment]
(PS: after a full install, `git clean -xdf` crashes with an out of memory exception 😅)

**Comment by erikbarke** [comment]
What kind of errors do you get, how do the tests fail? I just cloned the repo on a Windows 10 box with node v8.11.3 and npm v5.6.0:

```bash
git clone https://github.com/monounity/karma-typescript.git
cd karma-typescript
.\ci\install.bat
npm run ci
```
I get quite a few typings errors that need to be fixed, but the tests run 🤔

**Comment by erikbarke** [comment]
The errors you're getting are probably fixed in #292!

**Comment by vidartf** [comment]
Tried with latest pull from master. Getting a lot of type errors for jasmine/node, but also seeing errors like `Error: Cannot find module 'rgb-color'` during the bower test, and one of these:
```
> tests-integration-latest@3.0.13 dev:ci:core <repo-root>\tests\integration-latest
> gulp dev:ci --cwd . && karma start karma.conf.core.js --browsers ChromeHeadless --single-run

[14:21:52] Using gulpfile <repo-root>\gulpfile.js
[14:21:52] Starting 'clean'...
[14:21:52] Starting 'copy'...
[14:21:52] Finished 'clean' after 127 ms
[14:21:52] Finished 'copy' after 209 ms
[14:21:52] Starting 'dev:ci'...
[14:21:52] Finished 'dev:ci' after 53 μs
03 10 2018 14:21:56.240:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.9.2
03 10 2018 14:22:01.056:INFO [compiler.karma-typescript]: Compiled 2 files in 4787 ms.
03 10 2018 14:22:02.577:INFO [bundler.karma-typescript]: Bundled imports for 2 file(s) in 1017 ms.
03 10 2018 14:22:02.661:INFO [karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
03 10 2018 14:22:02.665:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
03 10 2018 14:22:02.682:INFO [launcher]: Starting browser ChromeHeadless
03 10 2018 14:22:03.549:INFO [HeadlessChrome 0.0.0 (Windows 10 0.0.0)]: Connected on socket FoJlUBu3ghCR3C_pAAAA with id 97096932
HeadlessChrome 0.0.0 (Windows 10 0.0.0) ERROR
  {
    "message": "Uncaught Error: Can't find constants [<repo-root>/node_modules/constants-browserify/constants.json] (required by <repo-root>/tests/integration-latest/src/node/core/core-module-tester.ts)\nat <repo-root>/src/client/commonjs.js:13:17\n\nError: Can't find constants [<repo-root>/node_modules/constants-browserify/constants.json] (required by <repo-root>/tests/integration-latest/src/node/core/core-module-tester.ts)\n    at require (<repo-root>/src/client/commonjs.js:13:23)\n    at <repo-root>/src/client/commonjs.js:18:24\n    at Object.global.wrappers.<repo-root>/tests/integration-latest/src/node/core/core-module-tester.ts.assert (src/node/core/core-module-tester.ts:4 <- src/node/core/core-module-tester.js:26:29)\n    at require (<repo-root>/src/client/commonjs.js:17:25)\n    at <repo-root>/src/client/commonjs.js:18:24\n    at Object.global.wrappers.<repo-root>/tests/integration-latest/src/node/core/core-module-tester.spec.ts.events (src/node/core/core-module-tester.spec.ts:2 <- src/node/core/core-module-tester.spec.js:4:28)\n    at require (<repo-root>/src/client/commonjs.js:17:25)\n    at <repo-root>/src/client/commonjs.js:32:9\n    at Array.forEach (<anonymous>)\n    at <repo-root>/src/client/commonjs.js:31:40",
    "str": "Uncaught Error: Can't find constants [<repo-root>/node_modules/constants-browserify/constants.json] (required by <repo-root>/tests/integration-latest/src/node/core/core-module-tester.ts)\nat <repo-root>/src/client/commonjs.js:13:17\n\nError: Can't find constants [<repo-root>/node_modules/constants-browserify/constants.json] (required by <repo-root>/tests/integration-latest/src/node/core/core-module-tester.ts)\n    at require (<repo-root>/src/client/commonjs.js:13:23)\n    at <repo-root>/src/client/commonjs.js:18:24\n    at Object.global.wrappers.<repo-root>/tests/integration-latest/src/node/core/core-module-tester.ts.assert (src/node/core/core-module-tester.ts:4 <- src/node/core/core-module-tester.js:26:29)\n    at require (<repo-root>/src/client/commonjs.js:17:25)\n    at <repo-root>/src/client/commonjs.js:18:24\n    at Object.global.wrappers.<repo-root>/tests/integration-latest/src/node/core/core-module-tester.spec.ts.events (src/node/core/core-module-tester.spec.ts:2 <- src/node/core/core-module-tester.spec.js:4:28)\n    at require (<repo-root>/src/client/commonjs.js:17:25)\n    at <repo-root>/src/client/commonjs.js:32:9\n    at Array.forEach (<anonymous>)\n    at <repo-root>/src/client/commonjs.js:31:40"
  }
HeadlessChrome 0.0.0 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.261 secs / 0 secs)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```

**Comment by erikbarke** [comment]
Closing in favor of #293.
