### ISSUE TITLE
Unable to resolve module that exists in devDependencies

### ISSUE THREAD

**Issue by xobotyi** [monounity/karma-typescript#313]
**Environment:**
*OS:* Win10
*NPM:* 6.6.0-next.1
*TypeScript:* 3.2.2
*karma-typescript:* 4.0.0-beta.2 (3.0.13 has same errors)

**Problem:**
I have types import iside my module:
```ts
import {
    DirectionProperty,
    OverflowXProperty,
    OverflowYProperty,
    PositionProperty,
    WebkitOverflowScrollingProperty,
} from "csstype";
```
It exists in node_modules, but tests run attempt brought an error:
```bash
11 01 2019 02:34:50.180:ERROR [karma-server]: Error: Unable to resolve module [csstype] from [E:/github.com/react-scrollbars-custom/src/Scrollbar.js]
{
  "basedir": "E:/github.com/react-scrollbars-custom/node_modules/csstype",
  "extensions": [
    ".js",
    ".json",
    ".ts",
    ".tsx"
  ],
  "moduleDirectory": [
    "node_modules"
  ],
  "modules": {
    "assert": "E:\\github.com\\react-scrollbars-custom\\node_modules\\assert\\assert.js",
    "buffer": "E:\\github.com\\react-scrollbars-custom\\node_modules\\buffer\\index.js",
    "child_process": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "cluster": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "console": "E:\\github.com\\react-scrollbars-custom\\node_modules\\console-browserify\\index.js",
    "constants": "E:\\github.com\\react-scrollbars-custom\\node_modules\\constants-browserify\\constants.json",
    "crypto": "E:\\github.com\\react-scrollbars-custom\\node_modules\\crypto-browserify\\index.js",
    "dgram": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "dns": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "domain": "E:\\github.com\\react-scrollbars-custom\\node_modules\\domain-browser\\source\\index.js",
    "events": "E:\\github.com\\react-scrollbars-custom\\node_modules\\events\\events.js",
    "fs": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "http": "E:\\github.com\\react-scrollbars-custom\\node_modules\\stream-http\\index.js",
    "https": "E:\\github.com\\react-scrollbars-custom\\node_modules\\https-browserify\\index.js",
    "module": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "net": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "os": "E:\\github.com\\react-scrollbars-custom\\node_modules\\os-browserify\\browser.js",
    "path": "E:\\github.com\\react-scrollbars-custom\\node_modules\\path-browserify\\index.js",
    "punycode": "E:\\github.com\\react-scrollbars-custom\\node_modules\\punycode\\punycode.js",
    "querystring": "E:\\github.com\\react-scrollbars-custom\\node_modules\\querystring-es3\\index.js",
    "readline": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "repl": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "stream": "E:\\github.com\\react-scrollbars-custom\\node_modules\\stream-browserify\\index.js",
    "_stream_duplex": "E:\\github.com\\react-scrollbars-custom\\node_modules\\readable-stream\\duplex.js",
    "_stream_passthrough": "E:\\github.com\\react-scrollbars-custom\\node_modules\\readable-stream\\passthrough.js",
    "_stream_readable": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\node_modules\\readable-stream\\readable.js",
    "_stream_transform": "E:\\github.com\\react-scrollbars-custom\\node_modules\\readable-stream\\transform.js",
    "_stream_writable": "E:\\github.com\\react-scrollbars-custom\\node_modules\\readable-stream\\writable.js",
    "string_decoder": "E:\\github.com\\react-scrollbars-custom\\node_modules\\string_decoder\\lib\\string_decoder.js",
    "sys": "E:\\github.com\\react-scrollbars-custom\\node_modules\\util\\util.js",
    "timers": "E:\\github.com\\react-scrollbars-custom\\node_modules\\timers-browserify\\main.js",
    "tls": "E:\\github.com\\react-scrollbars-custom\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
    "tty": "E:\\github.com\\react-scrollbars-custom\\node_modules\\tty-browserify\\index.js",
    "url": "E:\\github.com\\react-scrollbars-custom\\node_modules\\url\\url.js",
    "util": "E:\\github.com\\react-scrollbars-custom\\node_modules\\util\\util.js",
    "vm": "E:\\github.com\\react-scrollbars-custom\\node_modules\\vm-browserify\\index.js",
    "zlib": "E:\\github.com\\react-scrollbars-custom\\node_modules\\browserify-zlib\\lib\\index.js",
    "_process": "E:\\github.com\\react-scrollbars-custom\\node_modules\\process\\browser.js"
  },
  "filename": "",
  "paths": []
}
Error: Cannot find module 'csstype' from 'E:/github.com/react-scrollbars-custom/src'
    at E:\github.com\react-scrollbars-custom\node_modules\karma-typescript\dist\bundler\resolve\resolver.js:178:27
    at E:\github.com\react-scrollbars-custom\node_modules\browser-resolve\index.js:265:24
    at E:\github.com\react-scrollbars-custom\node_modules\resolve\lib\async.js:46:14
    at process (E:\github.com\react-scrollbars-custom\node_modules\resolve\lib\async.js:173:43)
    at ondir (E:\github.com\react-scrollbars-custom\node_modules\resolve\lib\async.js:188:17)
    at load (E:\github.com\react-scrollbars-custom\node_modules\resolve\lib\async.js:69:43)
    at onex (E:\github.com\react-scrollbars-custom\node_modules\resolve\lib\async.js:92:31)
    at E:\github.com\react-scrollbars-custom\node_modules\resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:161:21)

Process finished with exit code 1
```
I've tried to add it to devDependencies - didn't help. tsc does not emit any errors.

I suppose that problem is in absense of `index.js` file at `csstype`, due to it is only types library.

**Comment by erikbarke** [comment]
Do you have a test repo I could take a look at?

**Comment by xobotyi** [comment]
@erikbarke https://github.com/xobotyi/react-scrollbars-custom

**Comment by xobotyi** [comment]
Found one solution - add node_module to krama's `include` config and make import straight from the file: 
```ts
import {
    DirectionProperty,
    OverflowXProperty,
    OverflowYProperty,
    PositionProperty,
    WebkitOverflowScrollingProperty,
} from "./../node_modules/csstype";
```

**Comment by LouisWayne** [comment]
Still not working for me - and also can't figure out the cause of the issue

**Comment by LouisWayne** [comment]
I figured out - in my case, I am using TypesScript `v3.3.3333` with the option `esModuleInterop: true` - but `karma-typescript` doesn't support TS v3

**Comment by RenaudF** [comment]
@xobotyi 's solution worked out for me, I didn't even have to modify the karma's include list

**Comment by erikbarke** [comment]
Closing due to inactivity.
