### ISSUE TITLE
How to import form esm module?

### ISSUE THREAD

**Issue by RebeccaStevens** [monounity/karma-typescript#326]
Does this plugin support importing ECMAScript modules from js files?

I tried doing something like this but it didn't work:

```ts
// foo.ts
import { bar } from './bar.js';

export function foo(baz: number): number {
  return bar(baz) + 1;
}
```

```js
// bar.js
export function bar(qux: number): number {
  return qux * 2;
}
```

When I evaluate things in the browser, the line `var bar_js_1 = require("./bar.js");` sets `bar_js_1` to a string that contains the file contents of `bar.js` instead of loading the actual js.

**Comment by erikbarke** [comment]
Do you have an example repo?

**Comment by RebeccaStevens** [comment]
I've managed to resolve the issue with the value being set to a string (though I'm not sure how I did so). I'm still new to karma. Anyway, the js file is now being loaded but it's not being loaded as a module so I get the error `Uncaught SyntaxError: Unexpected token export`.

If I try and preprocess the file with karma-typescript (

```js
preprocessors: { '**/*.ts': ['karma-typescript'], 'utils/**/*.js': ['karma-typescript'] }
```

) I get the error

```
Error: No source found for /path/to/repo/utils/index.js!
Is there a mismatch between the Typescript compiler options and the Karma config?
```

Do you know how I can get this file to be preprocessed? Or Ideally how I can get all the files (js and ts) to run as modules? (I only need to test on browsers that have support for ECMAScript modules)

Here's a simple repo I just made: https://github.com/RebeccaStevens/karma-typescript-esm-demo

**Comment by erikbarke** [comment]
You don't have `--allowJs` in your tsconfig, have you tried that?

**Comment by RebeccaStevens** [comment]
If I add `allowJs` then then run `karma start` I get a weird error about the config being invalid:

```sh
$ karma start
15 03 2019 12:08:08.947:ERROR [config]: Invalid config file!
  TypeError: karma.conf.ts: Emit skipped
    at getOutput (/path/to/project/node_modules/ts-node/src/index.ts:338:15)
    at Object.compile (/path/to/project/node_modules/ts-node/src/index.ts:368:11)
    at Module.m._compile (/path/to/project/node_modules/ts-node/src/index.ts:414:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at require.extensions.(anonymous function) (/path/to/project/node_modules/ts-node/src/index.ts:417:12)
    at Object.require.extensions.(anonymous function) [as .ts] (/path/to/project/node_modules/ts-node/src/index.ts:417:12)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/path/to/project/karma.conf.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Module.m._compile (/path/to/project/node_modules/ts-node/src/index.ts:414:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Object.require.extensions.(anonymous function) (/path/to/project/node_modules/ts-node/src/index.ts:417:12)
error Command failed with exit code 1.
```
