### ISSUE TITLE
Mobx4 default export trap failing bundle

### ISSUE THREAD

**Issue by ShockiTV** [monounity/karma-typescript#334]
Hello,
I have issue using karma-typescript with old MobX4 (MobX5 require Proxies, so no IE11 ever) and I cannot upgrade to newer version.

```
  "devDependencies": {
    "karma": "^4.1.0",
    "karma-mocha": "^1.3.0",
    "karma-mocha-reporter": "^2.2.5",
    "karma-typescript": "^4.0.0",
    "mobx": "^4.9.4",
    "mocha": "^6.1.4",
    "typescript": "^3.4.5"
  }
```

MobX4 have this trap in exported module, which is failing karma-typescript bundling
```
// TODO: remove in some future build
if (process.env.NODE_ENV !== "production" &&
    typeof module !== "undefined" &&
    typeof module.exports !== "undefined") {
    var warnedAboutDefaultExport_1 = false;
    Object.defineProperty(module.exports, "default", {
        enumerable: false,
        get: function () {
            if (!warnedAboutDefaultExport_1) {
                warnedAboutDefaultExport_1 = true;
                console.warn("The MobX package does not have a default export. Use 'import { thing } from \"mobx\"' (recommended) or 'import * as mobx from \"mobx\"' instead.\"");
            }
            return undefined;
        }
    });
    [
        "extras",
        "Atom",
        "BaseAtom",
        "asFlat",
        "asMap",
        "asReference",
        "asStructure",
        "autorunAsync",
        "createTranformer",
        "expr",
        "isModifierDescriptor",
        "isStrictModeEnabled",
        "map",
        "useStrict",
        "whyRun"
    ].forEach(function (prop) {
        Object.defineProperty(module.exports, prop, {
            enumerable: false,
            get: function () {
                fail$$1("'" + prop + "' is no longer part of the public MobX api. Please consult the changelog to find out where this functionality went");
            },
            set: function () { }
        });
    });
}
```

with
```
START:
Chrome 74.0.3729 (Mac OS X 10.13.6) WARN: 'The MobX package does not have a default export. Use 'import { thing } from "mobx"' (recommended) or 'import * as mobx from "mobx"' instead."'
Chrome 74.0.3729 (Mac OS X 10.13.6) ERROR
  Uncaught TypeError: Cannot redefine property: default
  at http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:21:24
  
  TypeError: Cannot redefine property: default
      at Function.defineProperty (<anonymous>)
      at require (http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:21:24)
      at http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./Users/shock/workspace/test/mobx-karma-issue/src/used.ts.mobx (http://0.0.0.0:9876src/used.ts:1 <- src/used.js:20:26)
      at require (http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./Users/shock/workspace/test/mobx-karma-issue/src/file.ts../used (http://0.0.0.0:9876src/file.ts:1 <- src/file.js:20:26)
      at require (http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at http://0.0.0.0:9876node_modules/karma-typescript/dist/client/commonjs.js:32:9
      at Array.forEach (<anonymous>)
22 05 2019 15:45:35.151:WARN [Chrome 74.0.3729 (Mac OS X 10.13.6)]: Disconnected (0 times), because no message in 30000 ms.
Chrome 74.0.3729 (Mac OS X 10.13.6) ERROR
```
How can I help it to pass probably the bundling step? (it fail in runtime in browser, not while compiling)

How to reproduce? Just run `npm test` and connect with browser. Simple repo https://github.com/ShockiTV/mobx-karma-issue

When I follow the error source in browser, I get to
```
(function (global) {
    "use strict";
    global.__karmaTypescriptModules__ = {};
    var fn = 0;
    var id = 1;
    var map = 2;
    var require = function (filename, requiring, required) {
        var wrapper;
        var module = global.__karmaTypescriptModules__[filename];
        if (!module) {
            wrapper = global.wrappers[filename];
            if (!wrapper) {
                throw new Error("Can't find " + required + " [" + filename + "] (required by " + requiring + ")");
            }
            module = { exports: {}, id: wrapper[id], uri: filename };
            global.__karmaTypescriptModules__[filename] = module;
            wrapper[fn].call(module.exports, function (dependency) {
                return require(wrapper[map][dependency], filename, dependency);
            }, module, module.exports, filename.slice(0, filename.lastIndexOf("/")), filename);
            if (module.exports && !module.exports.default && isExtensible(module.exports)) {
                Object.defineProperty(module.exports, "default", {
                    configurable: true, enumerable: false, value: module.exports, writable: true
                });
            }
        }
        return module.exports;
    };
    var isExtensible = function (obj) {
        return (typeof obj === "function" || typeof obj === "object") && Object.isExtensible(obj);
    };
    (global.entrypointFilenames || []).forEach(function (filename) {
        require(filename, "commonjs.js", "entrypoint");
    });
})(this);
//# sourceMappingURL=commonjs.js.map
```

**Comment by erikbarke** [comment]
4.1.0 was just released with a commonjs fix, #323 (#316), does that fix change anything for you?
