### ISSUE TITLE
Getting compilation error at maybeWrapError

### ISSUE THREAD

**Issue by kshivam26** [monounity/karma-typescript#340]
Hi,
I have trying to include async, await in my files but I keep getting the below error.

**{ Error: COMPILATION ERROR
    at maybeWrapAsError (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\bluebird\js\release\nodeback.js:38:50
    at nextPreprocessor (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\karma\lib\preprocessor.js:22:14)
    at Object.callback (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\karma-typescript\dist\karma\preprocessor.js:19:36)
    at C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\karma-typescript\dist\compiler\compiler.js:83:20
    at Array.forEach (<anonymous>)
    at Compiler.onProgramCompiled (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\karma-typescript\dist\compiler\compiler.js:76:24)
    at Compiler.compileProject (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\karma-typescript\dist\compiler\compiler.js:62:14)
    at Compiler.<anonymous> (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\karma-typescript\dist\compiler\compiler.js:28:23)
    at invokeFunc (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\lodash\lodash.js:10335:23)
    at trailingEdge (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\lodash\lodash.js:10384:18)
    at Timeout.timerExpired [as _onTimeout] (C:\Users\kushivam\Source\Repos\SelfServeAdminExtn\node_modules\lodash\lodash.js:10372:18)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  cause: Error: COMPILATION ERROR**

I then started using promises and on resolve methods like promise.then(). Now when I am trying to mock the methods which return promises, it started giving the same error as above. The code that I am using to mock is 

**describe("Team_Helper_GetTeamDetailsByAreapathId", function () {
    it("Team_Helper_GetTeamDetailsByAreapathId-Id-null", function () {
        var teamHelper: TeamHelper = new TeamHelper();
        const data = GetPromisedTeamDetailsJson();
        var teamVM: TeamVM = new TeamVM(); 
        var areapathProfileVM:AreaPathProfileVM = null;
        let a = spyOn(services, 'GetTeamDetailsByAreapathId2').and.returnValue(Promise.resolve(data));
    });
});**

I am getting the above error when I include Promise.resolve().

My karma config is provided below:-
**module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',

        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine', 'karma-typescript'],

        // list of files / patterns to load in the browser
        files: [...]
}**

@erikbarke @xdamman @abraham

**Comment by erikbarke** [comment]
Closing due to inactivity.
