### ISSUE TITLE
coverage is unable to exclude test helper files

### ISSUE THREAD

**Issue by stevenalanstark** [monounity/karma-typescript#342]
Hello,

My project is written in typescript, and I am using project to generate coverage reports.

I have the report generating, but it's including any `./test/**/*.ts` files in the report.

For example, I have `./test/spec/foo.spec.ts` which will import `../helpers/foo_helper.ts`

My coverage report will include `../helpers/foo_helper.ts` in the report, which I do not want.

If I change the config so that these files aren't included, like `{ pattern: "./test/helpers/**/*.ts", included:false },` ( or by removing it all together ), then Karma will error with:

```
Uncaught Error: Can't find entrypoint [/test/helpers/foo_helper.ts] (required by my_lib.js)
  at node_modules/karma-typescript/dist/client/commonjs.js:13:17
  
  Error: Can't find entrypoint [/my_lib/test/helpers/foo_helper.ts] (required by commonjs.js)
      at require (node_modules/karma-typescript/dist/client/commonjs.js:13:23)
      at node_modules/karma-typescript/dist/client/commonjs.js:38:9
      at Array.forEach (<anonymous>)
      at node_modules/karma-typescript/dist/client/commonjs.js:37:40
      at node_modules/karma-typescript/dist/client/commonjs.js:40:3

```

So, I am forced to include these helper files in my report, or else remove these files all together and copy / paste the code into my .spec.ts files directly, which I want to avoid.

**Comment by erikbarke** [comment]
Closing due to inactivity.
