### ISSUE TITLE
Missing line number of origin typescript file in output

### ISSUE THREAD

**Issue by adumesny** [monounity/karma-typescript#374]
running into same issue as #142 with with latest rev

updated `karma-typescript` from `4.1.1` to `5.0.0` (or latest 5.0.2) the line number are incorrect in original .ts file

Output in `4.1.1`
```cmd
HeadlessChrome 80.0.3987 (Windows 10.0.0) gridstack grid.column should change column number and relayout items FAILED
  Error: Expected 4 to be 1.
    at <Jasmine>
    at UserContext.<anonymous> (spec/gridstack-spec.ts:279:51 <- spec/gridstack-spec.js:460:69)
```

Output in `5.0.2`
```cmd
HeadlessChrome 80.0.3987 (Windows 10.0.0) gridstack grid.column should change column number and relayout items FAILED
  Error: Expected 4 to be 1.
    at <Jasmine>
    at UserContext.<anonymous> (spec/gridstack-spec.ts:11:58 <- spec/gridstack-spec.js:10:314)
```

`gridstack-spec.ts:11:` is not the correct line number....
let me know if you need my tsconfig / karma config

**Comment by erikbarke** [comment]
Hey @adumesny, an example repo would more than welcome ☺️

**Comment by adumesny** [comment]
yeah, I know how that goes, maintaining a git repo lib myself... might be hard to create a case. I went back to 4.1.1 because of it.

Would pointing to my git repo with detail instructions work ? :)

**Comment by adumesny** [comment]
sorry meant to reply. 

1) get https://github.com/gridstack/gridstack.js (develop branch) and noticed "karma-typescript": "5.2.0", in package.json
2) mod some of the test file to have an error - say https://github.com/gridstack/gridstack.js/blob/develop/spec/gridstack-spec.ts#L51
3) yarn build
4) yarn test
--> get the error above but wrong line number
5) mod package.json to have "karma-typescript": "4.1.1" and rerun 'yarn test'
--> error message now has correct line number.
