### ISSUE TITLE
ERROR [karma-server]: UnhandledRejection: Cannot convert undefined or null to object and ERROR [karma-server]: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Skrigueztep** [monounity/karma-typescript#378]
15 05 2020 21:16:20.744:DEBUG [Chrome 81.0.4044.138 (Windows 10)]: CONNECTED -> EXECUTING
Chrome 81.0.4044.138 (Windows 10): Executed 1 of 1 SUCCESS (0 secs / 0.003 secs)
Chrome 81.0.4044.138 (Windows 10): Executed 1 of 1 SUCCESS (0.019 secs / 0.003 secs)
TOTAL: 1 SUCCESS
15 05 2020 21:16:20.780:ERROR [karma-server]: UnhandledRejection: Cannot convert undefined or null to object
15 05 2020 21:16:20.781:DEBUG [launcher]: Disconnecting all browsers
15 05 2020 21:16:20.781:DEBUG [launcher]: CAPTURED -> BEING_KILLED
15 05 2020 21:16:20.783:DEBUG [launcher]: BEING_KILLED -> BEING_FORCE_KILLED
15 05 2020 21:16:20.785:ERROR [karma-server]: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Reporter.create.<anonymous> (C:\Users\user\Desktop\project\node_modules\karma-typescript\dist\karma\reporter.js:80:40)
    at step (C:\Users\user\Desktop\project\node_modules\karma-typescript\dist\karma\reporter.js:33:23)
    at Object.next (C:\Users\user\Desktop\project\node_modules\karma-typescript\dist\karma\reporter.js:14:53)
    at fulfilled (C:\Users\user\Desktop\project\node_modules\karma-typescript\dist\karma\reporter.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
15 05 2020 21:16:20.790:DEBUG [coverage]: Writing coverage to C:/Users/user/Desktop/project/coverage/Chrome 81.0.4044.138 (Windows 10)
15 05 2020 21:16:20.879:DEBUG [launcher]: Process Chrome exited with code null and signal SIGTERM
15 05 2020 21:16:20.880:DEBUG [temp-dir]: Cleaning temp dir C:\Users\SKRIGU~1\AppData\Local\Temp\karma-68656864
15 05 2020 21:16:20.958:DEBUG [launcher]: Finished all browsers
15 05 2020 21:16:20.959:DEBUG [launcher]: BEING_FORCE_KILLED -> FINISHED
15 05 2020 21:16:20.959:DEBUG [launcher]: FINISHED -> FINISHED
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api@1.0.0 test:karma: `karma start karma.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the api@1.0.0 test:karma script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-05-16T02_16_20_999Z-debug.log

Warning? or Error? I haven´t problem at time, but thiscan be fixed?

**Comment by erikbarke** [comment]
Closing due to inactivity.
