### ISSUE TITLE
Node 12+ incompatible (work with in node 10)

### ISSUE THREAD

**Issue by Antoleb14** [monounity/karma-typescript#435]
Hi !
I encounter this error when launching test suite with node 12 and upper version:

```shell
12 02 2021 12:21:30.429:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.9.7
12 02 2021 12:22:04.931:INFO [compiler.karma-typescript]: Compiled 962 files in 34257 ms.
Since Acorn 8.0.0, options.ecmaVersion is required.
Defaulting to 2020, but this will stop working in the future.
12 02 2021 12:22:31.220:INFO [bundler.karma-typescript]: Bundled imports for 678 file(s) in 25777 ms.
12 02 2021 12:22:59.083:INFO [karma-server]: Karma v6.1.0 server started at http://localhost:9876/
12 02 2021 12:22:59.084:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
12 02 2021 12:22:59.088:INFO [launcher]: Starting browser ChromeHeadless
12 02 2021 12:22:59.583:INFO [Chrome Headless 90.0.4403.0 (Linux x86_64)]: Connected on socket _WEI9Jhis6WWNjTJAAAB with id 33624897
Chrome Headless 90.0.4403.0 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Uncaught TypeError: Cannot read property 'from' of undefined
  TypeError: Cannot read property 'from' of undefined
      at Object.global.wrappers./home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/safe-buffer/index.js.buffer (/tmp/karma-typescript-bundle--177189-Bu7Ja0Lpg0Z1-.js:422147:12)
      at require (/home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at /home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/jws/lib/sign-stream.js../tostring (/tmp/karma-typescript-bundle--177189-Bu7Ja0Lpg0Z1-.js:451185:14)
      at require (/home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at /home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/jws/index.js../lib/verify-stream (/tmp/karma-typescript-bundle--177189-Bu7Ja0Lpg0Z1-.js:451265:18)
      at require (/home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/client/commonjs.js:17:25)
      at /home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/client/commonjs.js:18:24
      at Object.global.wrappers./home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/jsonwebtoken/decode.js.jws (/tmp/karma-typescript-bundle--177189-Bu7Ja0Lpg0Z1-.js:451288:181)
```

The weird thing is that everything is OK when running in node 10.15.3... 
Do you have an idea of the problem ?

Versions used : 
Karma 6.1.0
karma-jasmine 4.0.1
karma-typescript 5.3.0
karma-typescript-angular2-transform 5.3.0
karma-typescript-es6-transform 5.3.0

And this is our configuration file :

```js
...
karmaTypescriptConfig: {
	bundlerOptions: {
		entrypoints: /\.spec\.ts$/,
		transforms: [
			require('karma-typescript-es6-transform')({
				presets: [
					['@babel/preset-env', {
						targets: {
							chrome: '60'
						}
					}]
				]
			}),
			require('karma-typescript-angular2-transform')
		],
		resolve: {
			alias: {
				dictionary: path.join(__dirname, 'config', 'dictionary.js'),
				common: path.resolve(path.join(__dirname, 'common')),
				'@client': path.resolve(__dirname, 'client'),
			},
			extensions: ['.js', '.ts', '.html']
		},
		sourceMap: true,
		exclude: ['node_modules'],
		acornOptions: {
			ecmaVersion: 2017,
		},
	},
	compilerOptions: {
		target: 'es5',
		lib: ['es2017', 'dom']
	},
	tsconfig: '../tsconfig.test.json',
	exclude: ['node_modules']
},
...
```

and tsconfig.test.json :

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "module": "commonjs",
    "noImplicitAny": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": true
  },
  "exclude": [
    "dist",
    "node_modules",
    "server",
    "**/*.test.js"
  ]
}
```

Thank you for your help

**Comment by erikbarke** [comment]
I messed up the 5.3.0 release, could you please try the 5.4.0 version and see if that helps?

**Comment by vladjerca** [comment]
@erikbarke Just some extra information. 

Version `5.3.0` works perfectly on my end with Node `v14.15.1`.

If I update to `5.4.0` the test execution nevers starts, it gets stuck after: 
```
13 02 2021 12:46:24.604:INFO [compiler.karma-typescript]: Compiling project using Typescript 4.1.3
13 02 2021 12:46:32.287:INFO [compiler.karma-typescript]: Compiled 266 files in 7578 ms.
```

**Comment by Antoleb14** [comment]
Thank you for your reply.

The 5.4.0 solve the initial problem !

But now, I got another issue with a JS file used in my test suite (and every other JS files used).

```
Error: /home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/test/unit/unitHelper.js: Unexpected token (25:6)
Transform function: 

function (context, callback) {
        if (!context.js) {
            return callback(undefined, false);
        }
        if (isEs6(context.js.ast)) {
            options.filename = context.filename;
            log.debug("Transforming %s", options.filename);
            try {
                context.source = babel.transform(context.source, options).code;
                context.js.ast = acorn.parse(context.source, { sourceType: "module", ecmaVersion: "latest" });
                return callback(undefined, true);
            }
            catch (error) {
                return callback(error, false);
            }
        }
        else {
            return callback(undefined, false);
        }
    }

    at Transformer.handleError (/home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/bundler/transformer.js:111:19)
    at /home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/bundler/transformer.js:91:27
    at transform (/home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript-es6-transform/dist/transform.js:56:24)
    at /home/alebel/Documents/dev/kxs01_soclesouscriptiondigitale/node_modules/karma-typescript/dist/bundler/transformer.js:85:17
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
The same error occurs also in node 14.x and 10.15.x

**Comment by zyf0330** [comment]
I use node v12.20.0, and tried karma-typescript 5.4.0 and 5.5.0, but this problem happened still.

```
Uncaught TypeError: Cannot read property 'prototype' of undefined
at http://localhost:9876/absolute/tmp/karma-typescript-bundle--82737-Yext4bPqlvnm-.js?f4b6a1e09a72d190e0f320fd4d3a9bf337fe83de:60921:33

TypeError: Cannot read property 'prototype' of undefined
    at Object.global.wrappers./project/node_modules/safer-buffer/safer.js.buffer (http://localhost:9876/absolute/tmp/karma-typescript-bundle--82737-Yext4bPqlvnm-.js?f4b6a1e09a72d190e0f320fd4d3a9bf337fe83de:60921:33)
    at require (http://localhost:9876/base/node_modules/karma-typescript/dist/client/commonjs.js?f5014f1e344ba3e2f0d92afe67b92f3001c46c90:17:25)
    at http://localhost:9876/base/node_modules/karma-typescript/dist/client/commonjs.js?f5014f1e344ba3e2f0d92afe67b92f3001c46c90:18:24
    at Object.global.wrappers./project/node_modules/asn1.js/lib/asn1/encoders/der.js.inherits (http://localhost:9876/absolute/tmp/karma-typescript-bundle--82737-Yext4bPqlvnm-.js?f4b6a1e09a72d190e0f320fd4d3a9bf337fe83de:60216:16)
    at require (http://localhost:9876/base/node_modules/karma-typescript/dist/client/commonjs.js?f5014f1e344ba3e2f0d92afe67b92f3001c46c90:17:25)
    at http://localhost:9876/base/node_modules/karma-typescript/dist/client/commonjs.js?f5014f1e344ba3e2f0d92afe67b92f3001c46c90:18:24
    at Object.global.wrappers./project/node_modules/asn1.js/lib/asn1/encoders/index.js../pem (http://localhost:9876/absolute/tmp/karma-typescript-bundle--82737-Yext4bPqlvnm-.js?f4b6a1e09a72d190e0f320fd4d3a9bf337fe83de:60514:16)
    at require (http://localhost:9876/base/node_modules/karma-typescript/dist/client/commonjs.js?f5014f1e344ba3e2f0d92afe67b92f3001c46c90:17:25)
    at http://localhost:9876/base/node_modules/karma-typescript/dist/client/commonjs.js?f5014f1e344ba3e2f0d92afe67b92f3001c46c90:18:24
    at Object.global.wrappers./project/node_modules/asn1.js/lib/asn1/api.js.inherits (http://localhost:9876/absolute/tmp/karma-typescript-bundle--82737-Yext4bPqlvnm-.js?f4b6a1e09a72d190e0f320fd4d3a9bf337fe83de:56986:18)
```

**Comment by erikbarke** [comment]
I'm really not sure the Node.js version is what's causing the problem here, I'm running v12.16.3 locally on OSX, the integration tests run on AppVeyor/Windows/Node.js v12.20.1, and Travis/Linux/Node.js v12.21.0 🤔 There must be something else at play here 😞

**Comment by vladjerca** [comment]
@erikbarke I'll try to see if I can find a bit more locally (I'll try to debug as much as possible).

In my case I don't get any errors, just gets stuck 😓

**Comment by erikbarke** [comment]
Hey guys, does @vladjerca's fix in #442 work for you? It's on npm in v5.5.1 ☺️

**Comment by vladjerca** [comment]
Just a note, after upgrading I also had to do a clean install (npm ci).

Worked like a charm afterwards 👍

**Comment by erikbarke** [comment]
Ok, feel free to reopen this issue if #442 didn't solve it!

**Comment by zarko-tg** [comment]
Been stuck here for some weeks now:
30 03 2021 08:57:29.633:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.8.4
30 03 2021 08:57:45.835:INFO [compiler.karma-typescript]: Compiled 225 files in 16115 ms.

Is there any way to debug/log what's going on?

(Using karma 6.3.2, karma-typescript & karma-typescript-es6-transform 5.5.1)

**Comment by vladjerca** [comment]
@zarko-tg if you run `npm ls acorn`, what's the output?

**Comment by zarko-tg** [comment]
@vladjerca

With 5.3.0, not hanging:

```
├─┬ @ionic/app-scripts@3.2.4
│ ├─┬ rollup-plugin-commonjs@8.2.6
│ │ └── acorn@5.7.3
│ └─┬ webpack@3.12.0
│   ├── acorn@5.7.3  deduped
│   └─┬ acorn-dynamic-import@2.0.2
│     └── acorn@4.0.13
└─┬ karma-typescript@5.3.0
  └── acorn@8.0.5
```

With 5.5.1, hanging:

```
├─┬ @ionic/app-scripts@3.2.4
│ ├─┬ rollup-plugin-commonjs@8.2.6
│ │ └── acorn@5.7.3
│ └─┬ webpack@3.12.0
│   ├── acorn@5.7.3  deduped
│   └─┬ acorn-dynamic-import@2.0.2
│     └── acorn@4.0.13
└─┬ karma-typescript@5.5.1
  └── acorn@8.1.0
```

I don't have any options.ecmaVersion set (yet).
Removing package-lock.json and reinstalling the deps didn't help.

**Comment by vladjerca** [comment]
@zarko-tg I had a similar issue after upgrading to `5.5.1` initially.

If you open `node_modules/acorn/package.json`. What version is in the top-level module. If that's not 8.1.0 then you're in the same situation I was in initially.

**Comment by zarko-tg** [comment]
@vladjerca yeah, node_modules/acorn/package.json has "version": "5.7.3".
While I can't really tell why the dependencies are tangled like this, I might go ahead with keeping the latest acorn version as a dep dependency, I does solve the hang. (so long as it doesn't break something else) Thanks for your tips.

**Comment by vladjerca** [comment]
@zarko-tg Always glad to help reduce someones pain if I've already been through it 😅

**Comment by Antoleb14** [comment]
Hi, just got some time to test the new version. The initial problem is solved but now i'm still stuck in karma-typescript 5.5.1 and node js 12.20 with the same problem than @zyf0330 

"Cannot read property 'prototype' of undefined"

I tried to npm ci as mentioned and also update acorn to latest (8.1.1) in dev deps but the problem still occurs.
In node 10.15, everything works, that's weird...

**Comment by vladjerca** [comment]
@Antoleb14 @erikbarke 

My personal opinion on the mater: considering that the latest LTS version is `14.16.1` , I'm not so convinced that the latest version of the pkg should continue supporting older versions of node 🤷🏼‍♂️
