### ISSUE TITLE
Not resolving package peerjs with karma-typescript (but works with webpack bundles and development)

### ISSUE THREAD

**Issue by digable1** [monounity/karma-typescript#436]
I have this specific package that I'm using, peerjs.  Everything is fine when using webpack such as for development via or generating bundles.  But not when I try to run unit tests via karma/jasmine.

Example log:

> 21 02 2021 07:51:56.657:INFO [compiler.karma-typescript]: Compiling project using Typescript 4.1.5
> 21 02 2021 07:51:57.915:INFO [compiler.karma-typescript]: Compiled 2 files in 1238 ms.
> 21 02 2021 07:51:58.669:ERROR [karma-server]: UncaughtException: Error: Unable to resolve module [../utils] from [c:\projects\test\node_modules\peerjs\dist\peerjs.min.js]
> {
>   "basedir": "c:/projects/test/src",
>   "extensions": [
>     ".js",
>     ".json",
>     ".mjs",
>     ".ts",
>     ".tsx"
>   ],
>   "moduleDirectory": [
>     "node_modules"
>   ],
>   "modules": {
>     "assert": "c:\\projects\\test\\node_modules\\assert\\build\\assert.js",
>     "buffer": "c:\\projects\\test\\node_modules\\buffer\\index.js",
>     "child_process": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "cluster": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "console": "c:\\projects\\test\\node_modules\\console-browserify\\index.js",
>     "constants": "c:\\projects\\test\\node_modules\\constants-browserify\\constants.json",
>     "crypto": "c:\\projects\\test\\node_modules\\crypto-browserify\\index.js",
>     "dgram": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "dns": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "domain": "c:\\projects\\test\\node_modules\\domain-browser\\source\\index.js",
>     "events": "c:\\projects\\test\\node_modules\\events\\events.js",
>     "fs": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "http": "c:\\projects\\test\\node_modules\\stream-http\\index.js",
>     "https": "c:\\projects\\test\\node_modules\\https-browserify\\index.js",
>     "module": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "net": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "os": "c:\\projects\\test\\node_modules\\os-browserify\\browser.js",
>     "path": "c:\\projects\\test\\node_modules\\path-browserify\\index.js",
>     "punycode": "c:\\projects\\test\\node_modules\\punycode\\punycode.js",
>     "querystring": "c:\\projects\\test\\node_modules\\querystring-es3\\index.js",
>     "readline": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "repl": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "stream": "c:\\projects\\test\\node_modules\\stream-browserify\\index.js",
>     "_stream_duplex": "c:\\projects\\test\\node_modules\\readable-stream\\lib\\_stream_duplex.js",
>     "_stream_passthrough": "c:\\projects\\test\\node_modules\\readable-stream\\lib\\_stream_passthrough.js",
>     "_stream_readable": "c:\\projects\\test\\node_modules\\readable-stream\\lib\\_stream_readable.js",
>     "_stream_transform": "c:\\projects\\test\\node_modules\\readable-stream\\lib\\_stream_transform.js",
>     "_stream_writable": "c:\\projects\\test\\node_modules\\readable-stream\\lib\\_stream_writable.js",
>     "string_decoder": "c:\\projects\\test\\node_modules\\string_decoder\\lib\\string_decoder.js",
>     "sys": "c:\\projects\\test\\node_modules\\util\\util.js",
>     "timers": "c:\\projects\\test\\node_modules\\timers-browserify\\main.js",
>     "tls": "c:\\projects\\test\\node_modules\\karma-typescript\\dist\\bundler\\resolve\\empty.js",
>     "tty": "c:\\projects\\test\\node_modules\\tty-browserify\\index.js",
>     "url": "c:\\projects\\test\\node_modules\\url\\url.js",
>     "util": "c:\\projects\\test\\node_modules\\util\\util.js",
>     "vm": "c:\\projects\\test\\node_modules\\vm-browserify\\index.js",
>     "zlib": "c:\\projects\\test\\node_modules\\browserify-zlib\\lib\\index.js",
>     "_process": "c:\\projects\\test\\node_modules\\process\\browser.js"
>   },
>   "filename": "",
>   "paths": []
> }
> Error: Cannot find module '../utils' from 'c:\projects\test\node_modules\peerjs\dist\peerjs.min.js'
>     at c:\projects\test\node_modules\karma-typescript\dist\bundler\resolve\resolver.js:180:27
>     at c:\projects\test\node_modules\browser-resolve\index.js:265:24
>     at c:\projects\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:160:17
>     at load (c:\projects\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:177:43)
>     at onex (c:\projects\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:202:17)
>     at c:\projects\test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:15:69
>     at FSReqCallback.oncomplete (fs.js:183:21)
> 

Here's my useless dummy code:

src/hello-world.ts:
```typescript
import Peer from "peerjs"

export function thisDoesNothingUseful(): number {
    const peer = new Peer();
    console.log(`Hello World, peer: ${peer}`);
    console.log(`Hello World`);
    return 5;
}
```

hello-world.spec.ts
```typescript
import * as helloWorld from "./hello-world"

describe('Quick test', () => {
    it('should do something (this is a useless test)', () => {
        expect(helloWorld.thisDoesNothingUseful()).toBe(5);
    });
});
```

karma.conf.js
```javascript
module.exports = (config) => {
  config.set({
    basePath: "src",
    browsers: [ 'FirefoxHeadless' ],
    files: [
      './**/*.ts'
    ],
    frameworks: [ 'jasmine', 'karma-typescript' ],
    karmaTypescriptConfig: {
      compilerOptions: {
        target: "es5",
        module: "commonjs",
        esModuleInterop: true,
        skipLibCheck: true
      },
      bundlerOptions: {
        transforms: [
            require("karma-typescript-es6-transform")()
        ]
      }
    },
    plugins: [
      'karma-chrome-launcher',
      'karma-firefox-launcher',
      'karma-jasmine',
      'karma-typescript',
      'karma-spec-reporter',
      'karma-coverage'
    ],
    preprocessors: {
      './**/*.spec.+(ts|tsx)': [ 'karma-typescript' ],
      './**/*.+(ts|tsx)': [ 'karma-typescript', 'coverage' ]
    },
    reporters: [ 'progress', 'coverage', 'spec', 'karma-typescript' ],
    singleRun: true
  });
}
```

package.json (ignore the extra dependencies not really needed for this rexample):
```json
{
  "name": "test",
  "version": "0.0.1",
  "description": "Quick test for peerjs and Karma",
  "main": "index.js",
  "scripts": {
    "start": "webpack serve",
    "test": "karma start"
  },
  "dependencies": {
    "peerjs": "^1.3.1"
  },
  "devDependencies": {
    "@as-pect/cli": "^6.0.0",
    "@types/eslint": "^7.2.6",
    "@types/jasmine": "^3.6.4",
    "@types/karma": "^6.1.0",
    "@types/node": "^14.14.31",
    "clean-webpack-plugin": "^3.0.0",
    "html-webpack-plugin": "^5.2.0",
    "istanbul": "^0.4.5",
    "jasmine": "^3.6.4",
    "jasmine-core": "^3.6.0",
    "jasmine-spec-reporter": "^6.0.0",
    "karma": "^6.1.1",
    "karma-coverage": "^2.0.3",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-firefox-launcher": "^2.1.0",
    "karma-jasmine": "^4.0.1",
    "karma-remap-istanbul": "^0.6.0",
    "karma-spec-reporter": "^0.0.32",
    "karma-typescript": "^5.4.0",
    "karma-typescript-es6-transform": "^5.4.0",
    "karma-typescript-mock": "^1.0.1",
    "karma-verbose-reporter": "^0.0.6",
    "ts-loader": "^8.0.17",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.1.5",
    "webpack": "^5.23.0",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
  }
}
```

Note:  It works if I don't have any references to peerJS.

src/hello-world.ts (with references to peerJS commented out):
```typescript
// import Peer from "peerjs"

export function thisDoesNothingUseful(): number {
    // const peer = new Peer();
    // console.log(`Hello World, peer: ${peer}`);
    console.log(`Hello World`);
    return 5;
}
```

Speculation:  I'm either doing something wrong or there's a bug.

Any clues?

**Comment by vladjerca** [comment]
@digable1 Out of curiosity, could you please try with version `5.3.0` of `karma-typescript-es6-transform` and `karma-typescript`?
