### ISSUE TITLE
Declarations included w/ pre processed files causes error

### ISSUE THREAD

**Issue by kylestlb** [monounity/karma-typescript#48]
Hi all, using typescript 1.75 and am bumping into a weird error:

`14 12 2016 11:54:10.354:ERROR [karma]: TypeError: Data must be a string or a buffer
  at Hash.update (crypto.js:74:16)
  at sha1 (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma/lib/preprocessor.js:11:8)
  at nextPreprocessor (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma/lib/preprocessor.js:32:18)
  at instrumentSource (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma-typescript/lib/preprocessor.js:110:13)
  at /Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma-typescript/lib/preprocessor.js:154:25
  at Bundler.bundle (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma-typescript/lib/bundlers/builtin/bundler.js:67:13)
  at Object.callback (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma-typescript/lib/preprocessor.js:150:29)
  at /Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma-typescript/lib/compiler.js:76:20
  at Array.forEach (native)
  at /Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/karma-typescript/lib/compiler.js:66:19
  at invokeFunc (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/lodash.debounce/index.js:160:19)
  at trailingEdge (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/lodash.debounce/index.js:207:14)
  at Timeout.timerExpired [as _onTimeout] (/Users/kyle/Documents/workspace/karma/DreamcatcherUX/node_modules/lodash.debounce/index.js:195:14)
  at ontimeout (timers.js:365:14)
  at tryOnTimeout (timers.js:237:5)
  at Timer.listOnTimeout (timers.js:207:5)
`

This only happens when I include my declarations folder with the rest of my *.ts source.  If I exclude the folder, it works, and opens phantomJS just fine.  I'm on node 7.2.1.

It looks like we are passing 'undefined' to the hash.update() function in preprocessor.js.  Am I supposed to exclude declaration files for karma-typescript to work?  Google-fu didn't really reveal much.

**Comment by erikbarke** [comment]
Hey @kylestlb, how are you excluding/including the typings files, is it in your Karma config? Are you able to run your tests successfully if you exclude the typings files?

**Comment by kylestlb** [comment]
Yeah - I used a globbing pattern to include all *.ts files... but I'll just break out my declarations to build separately.  I'm still unsure if it's really a bug since perhaps the d.ts files maybe aren't supposed to be included?

Anyway, I can work around it, but was just curious if this was intended or not.

**Comment by erikbarke** [comment]
Ah, ok! The typings files are only needed in the compiling step, they're not needed when running the unit tests or when deploying the application. However, typings files should be excluded by default by the preprocessor to prevent the behavior you're describing, so I think there's a bug in there somewhere, I just haven't been able to reproduce it...

**Comment by sir-marc** [comment]
@kylestlb you can prevent loading the d.ts files in with a regex `!(d).ts`

**Comment by erikbarke** [comment]
Stupid oversight on my part, the Typescript api changes between versions...

@kylestlb, does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.
