### ISSUE TITLE
browserify trying to include dev dependencies

### ISSUE THREAD

**Issue by moshmage** [monounity/karma-typescript#53]
As browserify *and some other npm modules* don't go along (looking at [websocket 1.0.1](https://github.com/websockets/ws/commit/e54d45fbab3b19c2940e9057ce1e7b8f105873e0)) there needs to be a way of ignoring certain modules to *not be required/bundled*. 

As it happens now, for some reason, karma-typescript is trying to require a `devDependency` from `ws` (which, it shouldn't to be fair, but it is).

People over at WS claim that bundlers [should](https://github.com/websockets/ws/pull/661#issuecomment-170269354)...
> learn how to ignore optional dependencies instead of forcing packages to become compatible the build systems.

While a bit pricky, it does make *some* sense. 
SocketIO-Client managed to "fix" this by saying to webpack/browserify "ignore ws" (more on [this issue](https://github.com/socketio/socket.io-client/issues/933))
It would be nice if we could control that as well.

Logs:

```logtalk
19 12 2016 14:29:55.948:ERROR [karma]: Error: Cannot find module 'utf-8-validate' from 'c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\ws\lib'
    at Function.module.exports [as sync] (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\browser-resolve\node_modules\resolve\lib\sync.js:33:11)
    at Function.resolve.sync (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\browser-resolve\index.js:321:21)
    at resolve (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:226:50)
    at resolveModules (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:205:9)
    at c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:244:28
    at Array.forEach (native)
    at addDependencies (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:242:27)
    at resolveModules (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:217:9)
    at c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:244:28
    at Array.forEach (native)
    at addDependencies (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:242:27)
    at resolveModules (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:217:9)
    at c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:244:28
    at Array.forEach (native)
    at addDependencies (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:242:27)
    at resolveModules (c:\Users\Mosh Mage\WebstormProjects\rxjs-SocketIO-client\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:217:9)
```

`utf-8-validate` isn't installed in node_modules because itself is a binary DEV dependency of the `ws` module. Why we are trying to include it in our build is beyond me.

You can get a fresh look at it [this branch](https://gitlab.com/moshmage/rxjs-socket.io/tree/implement-test) via `karma start`

**Comment by erikbarke** [comment]
I managed to workaround the `ws` issue by ignoring it in the bundler (same ugly workaround as in the webpack issue you you linked):
```javascript
karmaTypescriptConfig: {
    bundlerOptions: {
       ignoredModuleNames: ["ws"]
    }
}
```

Now the integration test crashes on `socket.io`trying to load package.json from `socket.io-client`, I'll have to fix that.

This is an age-old bundler conundrum; the bundler blindly parses all dependencies recursively looking for the word `require` without knowing in what context a module is required...

**Comment by erikbarke** [comment]
@moshmage, `socket.io` uses the file system doing stuff like `var read = require('fs').readFileSync;` and `read(require.resolve('socket.io-client/dist/socket.io.min.js'), 'utf-8');` which means it can't be run in a browser with Karma and karma-typescript 😞

A lot of bugs have been fixed and new functionality has been added thanks to this issue, but this is as far as we get, I can't run your example project in a browser due to the nature of `socket.io`.
