### ISSUE TITLE
Cannot trigger test run

### ISSUE THREAD

**Issue by segrey** [monounity/karma-typescript#58]
Run karma server with
```
karma start karma.conf.js
```
Everything works as expected. Trigger a test run using
```
karma run
```
An exception is thrown
```
Unhandled rejection TypeError: Cannot read property 'push' of undefined
    at /home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/reporters/multi.js:6:24
    at Array.forEach (native)
    at MultiReporter.addAdapter (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/reporters/multi.js:5:15)
    at Server.<anonymous> (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/middleware/runner.js:41:18)
    at Server.g (events.js:292:16)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Executor.schedule (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/executor.js:26:15)
    at Server.<anonymous> (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/server.js:349:16)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at emit (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/file-list.js:77:19)
    at List.self._emitModified (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/file-list.js:81:17)
    at /home/segrey/issues/WEB-24776/karma_typescript/node_modules/karma/lib/file-list.js:205:10
    at tryCatcher (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/segrey/issues/WEB-24776/karma_typescript/node_modules/bluebird/js/release/promise.js:510:31)
```

Originally reported in https://youtrack.jetbrains.com/issue/WEB-24776

**Comment by segrey** [comment]
Seems it's a regression after removing `baseReporterDecorator` in https://github.com/monounity/karma-typescript/commit/8f0726a2e34b636b198a6f50aec414fa068a816a.
Creating an empty `this.adapters` array in `karma-typescript/lib/reporter.js > Reporter.create` would fix the issue as well (without adding back `baseReporterDecorator`).

**Comment by erikbarke** [comment]
Hey @segrey, thanks! Does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?

**Comment by marpe** [comment]
@erikbarke worked for me 👍

**Comment by segrey** [comment]
@erikbarke karma-typescript@2.1.6 works for me too. Thanks for the quick turnaround!
